//
// AccountType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Тип счёта. */

public enum AccountType: String, Codable {
    case unspecified = "ACCOUNT_TYPE_UNSPECIFIED"
    case tinkoff = "ACCOUNT_TYPE_TINKOFF"
    case tinkoffIis = "ACCOUNT_TYPE_TINKOFF_IIS"
    case investBox = "ACCOUNT_TYPE_INVEST_BOX"
}
