//
// Bond.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Объект передачи информации об облигации. */

public struct Bond: Decodable {
    public let uid: String
    public let ticker: String
    public let classCode: String
    public let positionUid: String
    public let brand: BrandData
    public let lot: Int
    public let currency: String
    public let name: String
    public let exchange: String
    public let realExchange: RealExchange
    public let countryOfRisk: String
    public let countryOfRiskName: String
    public let tradingStatus: SecurityTradingStatus
    public let klong: Quotation?
    public let kshort: Quotation?
    public let dlong: Quotation?
    public let dshort: Quotation?
    public let dlongMin: Quotation?
    public let dshortMin: Quotation?
    public let minPriceIncrement: Quotation?
    public let first1minCandleDate: Date?
    public let first1dayCandleDate: Date?
    public let shortEnabledFlag: Bool
    public let otcFlag: Bool
    public let buyAvailableFlag: Bool
    public let sellAvailableFlag: Bool
    public let apiTradeAvailableFlag: Bool
    public let forIisFlag: Bool
    public let forQualInvestorFlag: Bool
    public let weekendFlag: Bool
    public let blockedTcaFlag: Bool

    public let figi: String
    public let isin: String
    public let assetUid: String
    public let sector: String

    /// Форма выпуска.
    ///
    /// Возможные значения:
    /// - **documentary** — документарная
    /// - **non_documentary** — бездокументарная
    public let issueKind: String
    public let issueSize: String
    public let issueSizePlan: String
    public let couponQuantityPerYear: Int
    public let nominal: MoneyValue
    public let initialNominal: MoneyValue
    public let placementPrice: MoneyValue
    public let aciValue: MoneyValue
    public let riskLevel: RiskLevel
    public let liquidityFlag: Bool

    /// Признак облигации с плавающим купоном.
    public let floatingCouponFlag: Bool

    /// Признак бессрочной облигации.
    public let perpetualFlag: Bool

    /// Признак облигации с амортизацией долга.
    public let amortizationFlag: Bool

    /// Признак субординированной облигации.
    public let subordinatedFlag: Bool

    public let stateRegDate: Date?
    public let placementDate: Date?
    public let maturityDate: Date?
}
