//
// CancelOrderResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Результат отмены торгового поручения. */

public struct CancelOrderResponse: Decodable {
    public let time: Date
    public let responseMetadata: ResponseMetadata?
}
