//
// CloseSandboxAccountRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Запрос закрытия счёта в песочнице. */

public struct CloseSandboxAccountRequest: Encodable {
    public let accountId: String
}
