//
// FutureResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Данные по фьючерсу. */

public struct FutureResponse: Decodable {
    public let instrument: Future
}
