//
// GetCandlesRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Запрос исторических свечей. */

public struct GetCandlesRequest: Codable {
    public let instrumentId: String
    public let from: Date
    public let to: Date
    public let interval: CandleInterval
    public let limit: Int?
}
