//
// GetCandlesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Список свечей. */

public struct GetCandlesResponse: Codable {
    public let candles: [HistoricCandle]
}
