//
// GetOrderPriceResponseExtraFuture.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct GetOrderPriceResponseExtraFuture: Decodable {
    public let initialMargin: MoneyValue?

    public init(initialMargin: MoneyValue? = nil) {
        self.initialMargin = initialMargin
    }
}
