//
// Option.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Опцион. */

public struct Option: Decodable {
    public let uid: String
    public let ticker: String
    public let classCode: String
    public let positionUid: String
    public let brand: BrandData
    public let lot: Int
    public let currency: String
    public let name: String
    public let exchange: String
    public let realExchange: RealExchange
    public let countryOfRisk: String
    public let countryOfRiskName: String
    public let tradingStatus: SecurityTradingStatus
    public let klong: Quotation?
    public let kshort: Quotation?
    public let dlong: Quotation?
    public let dshort: Quotation?
    public let dlongMin: Quotation?
    public let dshortMin: Quotation?
    public let minPriceIncrement: Quotation?
    public let first1minCandleDate: Date?
    public let first1dayCandleDate: Date?
    public let shortEnabledFlag: Bool
    public let otcFlag: Bool
    public let buyAvailableFlag: Bool
    public let sellAvailableFlag: Bool
    public let apiTradeAvailableFlag: Bool
    public let forIisFlag: Bool
    public let forQualInvestorFlag: Bool
    public let weekendFlag: Bool
    public let blockedTcaFlag: Bool

    public let basicAssetPositionUid: String
    public let direction: OptionDirection
    public let paymentType: OptionPaymentType
    public let style: OptionStyle
    public let settlementType: OptionSettlementType
    public let settlementCurrency: String
    public let assetType: String
    public let basicAsset: String
    public let sector: String
    public let basicAssetSize: Quotation
    public let strikePrice: MoneyValue
    public let expirationDate: Date
    public let firstTradeDate: Date
    public let lastTradeDate: Date
}
