//
// PortfolioPosition.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Позиции портфеля. */

public struct PortfolioPosition: Decodable {
    public let instrumentUid: String
    public let figi: String
    public let positionUid: String
    public let instrumentType: String
    public let quantity: Quotation
    public let blocked: Bool

    public let currentPrice: MoneyValue?
    public let averagePositionPrice: MoneyValue?
    public let averagePositionPriceFifo: MoneyValue?
    public let expectedYield: Quotation?
    public let expectedYieldFifo: Quotation?
    public let blockedLots: Quotation?
    public let currentNkd: MoneyValue?
    public let varMargin: MoneyValue?
}
