//
// PostOrderRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Запрос выставления торгового поручения. */

public struct PostOrderRequest: Encodable {
    public let accountId: String
    public let instrumentId: String

    /// Идентификатор ключа идемпотентности в формате UID. Максимальная длина 36 символов.
    public let orderId: String
    public let orderType: OrderType
    public let direction: OrderDirection
    public let quantity: String
    public let priceType: PriceType?
    public let price: Quotation?
    public let timeInForce: TimeInForceType?

    public init(
        accountId: String,
        instrumentId: String,
        orderId: String,
        orderType: OrderType,
        direction: OrderDirection,
        quantity: String,
        priceType: PriceType? = nil,
        price: Quotation? = nil,
        timeInForce: TimeInForceType? = nil
    ) {
        self.accountId = accountId
        self.instrumentId = instrumentId
        self.orderId = orderId
        self.orderType = orderType
        self.direction = direction
        self.quantity = quantity
        self.priceType = priceType
        self.price = price
        self.timeInForce = timeInForce
    }
}
