//
// SandboxPayInResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Результат пополнения счёта, текущий баланс. */

public struct SandboxPayInResponse: Decodable {
    public let balance: MoneyValue
}
