//
// TakeProfitType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Тип TakeProfit заявки. */

public enum TakeProfitType: String, Codable {
    case unspecified = "TAKE_PROFIT_TYPE_UNSPECIFIED"
    case regular = "TAKE_PROFIT_TYPE_REGULAR"
    case trailing = "TAKE_PROFIT_TYPE_TRAILING"
}
