//
// AccountStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Статус счёта. */

public enum AccountStatus: String, Codable {
    case unspecified = "ACCOUNT_STATUS_UNSPECIFIED"
    case new = "ACCOUNT_STATUS_NEW"
    case open = "ACCOUNT_STATUS_OPEN"
    case closed = "ACCOUNT_STATUS_CLOSED"
}
