//
// CurrencyResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Данные по валюте. */

public struct CurrencyResponse: Decodable {
    public let instrument: Currency
}
