//
// EtfResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Данные по фонду. */

public struct EtfResponse: Decodable {
    public let instrument: Etf
}
