//
// GetBondCouponsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Купоны по облигации. */

public struct GetBondCouponsResponse: Decodable {
    public let events: [Coupon]
}
