//
// GetClosePricesRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Запрос цен закрытия торговой сессии по инструментам. */

public struct GetClosePricesRequest: Encodable {
    public let instruments: [InstrumentClosePriceRequest]
}
