//
// GetClosePricesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Цены закрытия торговой сессии по инструментам. */

public struct GetClosePricesResponse: Decodable {
    public let closePrices: [InstrumentClosePriceResponse]
}
