//
// GetLastPricesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Список цен последних сделок. */

public struct GetLastPricesResponse: Decodable {
    public let lastPrices: [LastPrice]
}
