//
// GetOrdersRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Запрос получения списка активных торговых поручений. */

public struct GetOrdersRequest: Encodable {
    public let accountId: String
}
