//
// GetOrderPriceRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct GetOrderPriceRequest: Encodable {
    public var accountId: String
    public var instrumentId: String
    public var price: Quotation?
    public var direction: OrderDirection
    public var quantity: String
}
