//
// GetOrderPriceResponseExtraBond.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct GetOrderPriceResponseExtraBond: Decodable {
    public let aciValue: MoneyValue?
    public let nominalConversionRate: Quotation?

    public init(aciValue: MoneyValue? = nil, nominalConversionRate: Quotation? = nil) {
        self.aciValue = aciValue
        self.nominalConversionRate = nominalConversionRate
    }
}
