//
// InstrumentsRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Запрос получения инструментов. */

public struct InstrumentsRequest: Encodable {
    public let instrumentStatus: InstrumentStatus
}
