//
// InstrumentShort.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Краткая информация об инструменте. */

public struct InstrumentShort: Decodable {
    public let uid: String
    public let figi: String
    public let ticker: String
    public let classCode: String
    public let isin: String
    public let positionUid: String
    public let instrumentType: String
    public let name: String
    public let instrumentKind: InstrumentType

    public let apiTradeAvailableFlag: Bool
    public let forIisFlag: Bool
    public let forQualInvestorFlag: Bool
    public let weekendFlag: Bool
    public let blockedTcaFlag: Bool

    public let first1minCandleDate: Date?
    public let first1dayCandleDate: Date?
}
