//
// InstrumentResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Данные по инструменту. */

public struct InstrumentResponse: Decodable {
    public let instrument: Instrument
}
