//
// LastPrice.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Информация о цене последней сделки. */

public struct LastPrice: Decodable {
    public let instrumentUid: String
    public let figi: String
    public let price: Quotation?
    /// Время получения последней цены в часовом поясе UTC по времени биржи.
    public let time: Date?
}
