//
// OpenSandboxAccountResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct OpenSandboxAccountResponse: Decodable {
    /** Номер открытого счёта в песочнице. */
    public let accountId: String
}
