//
// OperationItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Данные об операции. */

public struct OperationItem: Decodable {
    /// Идентификатор операции, может меняться с течением времени.
    public let id: String
    public let cursor: String
    public let brokerAccountId: String
    public let parentOperationId: String
    public let name: String
    public let date: Date
    public let description: String
    public let type: OperationType
    public let state: OperationState
    public let payment: MoneyValue
    public let price: MoneyValue

    public let instrumentUid: String
    public let figi: String
    public let instrumentType: String
    public let instrumentKind: InstrumentType
    public let positionUid: String
    public let assetUid: String

    /// Количество единиц инструмента.
    public let quantity: String

    /// Неисполненный остаток по сделке.
    public let quantityRest: String

    /// Исполненный остаток.
    public let quantityDone: String

    /// Причина отмены операции.
    public let cancelReason: String

    /// Дата и время снятия заявки.
    public let cancelDateTime: Date?
    public let tradesInfo: OperationItemTrades?

    // MARK: not available in sandbox

    public let commission: MoneyValue?
    public let yield: MoneyValue?
    public let yieldRelative: Quotation?
    public let accruedInt: MoneyValue?
}
