//
// OperationItemTrade.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Сделка по операции. */

public struct OperationItemTrade: Decodable {
    public let num: String
    public let date: Date
    public let quantity: String
    public let price: MoneyValue
    public let yield: MoneyValue
    public let yieldRelative: Quotation
}
