//
// OptionResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Данные по опциону. */

public struct OptionResponse: Decodable {
    public let instrument: Option
}
