//
// OptionPaymentType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Тип расчетов по опциону. */

public enum OptionPaymentType: String, Codable {
    case unspecified = "OPTION_PAYMENT_TYPE_UNSPECIFIED"
    case premium = "OPTION_PAYMENT_TYPE_PREMIUM"
    case marginal = "OPTION_PAYMENT_TYPE_MARGINAL"
}
