//
// PortfolioResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Текущий портфель по счёту. */

public struct PortfolioResponse: Decodable {
    public let totalAmountShares: MoneyValue
    public let totalAmountBonds: MoneyValue
    public let totalAmountEtf: MoneyValue
    public let totalAmountCurrencies: MoneyValue
    public let totalAmountFutures: MoneyValue
    public let positions: [PortfolioPosition]
    public let accountId: String
    public let totalAmountOptions: MoneyValue
    public let totalAmountSp: MoneyValue
    public let totalAmountPortfolio: MoneyValue
    public let virtualPositions: [VirtualPortfolioPosition]
    public let expectedYield: Quotation?
}
