//
// RealExchange.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Реальная площадка исполнения расчётов. */

public enum RealExchange: String, Codable {
    case unspecified = "REAL_EXCHANGE_UNSPECIFIED"
    case moex = "REAL_EXCHANGE_MOEX"
    case rts = "REAL_EXCHANGE_RTS"
    case otc = "REAL_EXCHANGE_OTC"
    case dealer = "REAL_EXCHANGE_DEALER"
}
