//
// ResponseMetadata.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct ResponseMetadata: Decodable {
    public let trackingId: String
    public let serverTime: Date
}
