//
// Order.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Массив предложений/спроса. */

public struct Order: Decodable {
    public let price: Quotation
    public let quantity: String
}
