//
// ShareType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Тип акций. */

public enum ShareType: String, Codable {
    case unspecified = "SHARE_TYPE_UNSPECIFIED"
    case common = "SHARE_TYPE_COMMON"
    case preferred = "SHARE_TYPE_PREFERRED"
    case adr = "SHARE_TYPE_ADR"
    case gdr = "SHARE_TYPE_GDR"
    case mlp = "SHARE_TYPE_MLP"
    case nyRegShrs = "SHARE_TYPE_NY_REG_SHRS"
    case closedEndFund = "SHARE_TYPE_CLOSED_END_FUND"
    case reit = "SHARE_TYPE_REIT"
}
