//
// TrailingData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct TrailingData: Encodable {
    public let indent: Quotation
    public let indentType: TrailingValueType
    public let spread: Quotation
    public let spreadType: TrailingValueType
}
