//
// CancelOrderRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Запрос отмены торгового поручения. */

public struct CancelOrderRequest: Encodable {
    public let accountId: String
    public let orderId: String
}
