//
// GetAccountsRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Запрос получения счетов пользователя. */

public struct GetAccountsRequest: Encodable {
    public let status: AccountStatus?
}
