//
// GetLastPricesRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Запрос получения цен последних сделок. */

public struct GetLastPricesRequest: Encodable {
    public let instrumentId: [String]
}
