//
// GetStopOrdersRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Запрос получения списка активных стоп-заявок. */

public struct GetStopOrdersRequest: Encodable {
    public let accountId: String
}
