//
// OrderDirection.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Направление операции. */

public enum OrderDirection: String, Codable {
    case unspecified = "ORDER_DIRECTION_UNSPECIFIED"
    case buy = "ORDER_DIRECTION_BUY"
    case sell = "ORDER_DIRECTION_SELL"
}
