//
// Account.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Информация о счёте. */

public struct Account: Codable {
    /** Идентификатор счёта. */
    public let id: String
    public let type: AccountType
    /** Название счёта. */
    public let name: String
    public let status: AccountStatus
    /** Дата открытия счёта в часовом поясе UTC. */
    public let openedDate: Date
    /** Дата закрытия счёта в часовом поясе UTC. */
    public let closedDate: Date?
    public let accessLevel: AccessLevel
}
