//
// BondResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Информация об облигации. */

public struct BondResponse: Codable {
    public let instrument: Bond
}
