//
// EtfsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Данные по фондам. */

public struct EtfsResponse: Codable {
    public let instruments: [Etf]
}
