//
// ExchangeOrderType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Тип выставляемой заявки. */

public enum ExchangeOrderType: String, Codable {
    case unspecified = "EXCHANGE_ORDER_TYPE_UNSPECIFIED"
    case market = "EXCHANGE_ORDER_TYPE_MARKET"
    case limit = "EXCHANGE_ORDER_TYPE_LIMIT"
}
