//
// FindInstrumentResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Результат поиска инструментов. */

public struct FindInstrumentResponse: Codable {
    public let instruments: [InstrumentShort]
}
