//
// GetOperationsByCursorRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Запрос списка операций по счёту с пагинацией. */

public struct GetOperationsByCursorRequest: Codable {
    public let accountId: String
    public let limit: Int
    public let state: OperationState
    public let withoutCommissions: Bool
    public let withoutTrades: Bool
    public let withoutOvernights: Bool

    public let instrumentId: String?
    public let from: Date?
    public let to: Date?
    public let cursor: String?
    public let operationTypes: [OperationType]

    public init(
        accountId: String,
        instrumentId: String? = nil,
        from: Date? = nil,
        to: Date? = nil,
        cursor: String? = nil,
        limit: Int = 100,
        operationTypes: [OperationType] = [],
        state: OperationState = .unspecified,
        withoutCommissions: Bool = false,
        withoutTrades: Bool = false,
        withoutOvernights: Bool = false
    ) {
        self.accountId = accountId
        self.instrumentId = instrumentId
        self.from = from
        self.to = to
        self.cursor = cursor
        self.limit = limit
        self.operationTypes = operationTypes
        self.state = state
        self.withoutCommissions = withoutCommissions
        self.withoutTrades = withoutTrades
        self.withoutOvernights = withoutOvernights
    }
}
