//
// GetOrderBookRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Запрос стакана. */

public struct GetOrderBookRequest: Codable {
    public let instrumentId: String
    public let depth: Int
}
