//
// GetOrderPriceResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct GetOrderPriceResponse: Codable {
    public let totalOrderAmount: MoneyValue
    public let initialOrderAmount: MoneyValue
    public let lotsRequested: String
    public let executedCommission: MoneyValue
    public let executedCommissionRub: MoneyValue
    public let dealCommission: MoneyValue

    public let serviceCommission: MoneyValue?
    public let extraBond: GetOrderPriceResponseExtraBond?
    public let extraFuture: GetOrderPriceResponseExtraFuture?
}
