//
// InstrumentClosePriceResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Цена закрытия торговой сессии по инструменту. */

public struct InstrumentClosePriceResponse: Codable {
    /** Uid инструмента. */
    public let instrumentUid: String
    /** Figi инструмента. */
    public let figi: String?
    public let price: Quotation?
    public let eveningSessionPrice: Quotation?
    /** Дата совершения торгов. */
    public let time: Date?
}
