//
// InstrumentRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Запрос получения инструмента по идентификатору. */

public struct InstrumentRequest: Codable {
    public let idType: InstrumentIdType
    public let classCode: String?
    public let id: String?

    public init(idType: InstrumentIdType, classCode: String? = nil, id: String? = nil) {
        self.idType = idType
        self.classCode = classCode
        self.id = id
    }
}
