//
// InstrumentIdType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public enum InstrumentIdType: String, Codable {
    case unspecified = "INSTRUMENT_ID_UNSPECIFIED"
    case typeFigi = "INSTRUMENT_ID_TYPE_FIGI"
    case typeTicker = "INSTRUMENT_ID_TYPE_TICKER"
    case typeUid = "INSTRUMENT_ID_TYPE_UID"
    case typePositionUid = "INSTRUMENT_ID_TYPE_POSITION_UID"
}
