//
// InstrumentType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Тип инструмента. */

public enum InstrumentType: String, Codable {
    case unspecified = "INSTRUMENT_TYPE_UNSPECIFIED"
    case bond = "INSTRUMENT_TYPE_BOND"
    case share = "INSTRUMENT_TYPE_SHARE"
    case currency = "INSTRUMENT_TYPE_CURRENCY"
    case etf = "INSTRUMENT_TYPE_ETF"
    case futures = "INSTRUMENT_TYPE_FUTURES"
    case sp = "INSTRUMENT_TYPE_SP"
    case option = "INSTRUMENT_TYPE_OPTION"
    case clearingCertificate = "INSTRUMENT_TYPE_CLEARING_CERTIFICATE"
    case index = "INSTRUMENT_TYPE_INDEX"
    case commodity = "INSTRUMENT_TYPE_COMMODITY"
}
