//
// RiskLevel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Уровень риска облигации. */

public enum RiskLevel: String, Codable {
    case unspecified = "RISK_LEVEL_UNSPECIFIED"
    case low = "RISK_LEVEL_LOW"
    case moderate = "RISK_LEVEL_MODERATE"
    case high = "RISK_LEVEL_HIGH"
}
