//
// SandboxPayInRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Запрос пополнения счёта в песочнице. */

public struct SandboxPayInRequest: Encodable {
    public let accountId: String
    public let amount: MoneyValue
}
