//
// SecurityTradingStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public enum SecurityTradingStatus: String, Codable {
    case unspecified = "SECURITY_TRADING_STATUS_UNSPECIFIED"
    case notAvailableForTrading = "SECURITY_TRADING_STATUS_NOT_AVAILABLE_FOR_TRADING"
    case openingPeriod = "SECURITY_TRADING_STATUS_OPENING_PERIOD"
    case closingPeriod = "SECURITY_TRADING_STATUS_CLOSING_PERIOD"
    case breakInTrading = "SECURITY_TRADING_STATUS_BREAK_IN_TRADING"
    case normalTrading = "SECURITY_TRADING_STATUS_NORMAL_TRADING"
    case closingAuction = "SECURITY_TRADING_STATUS_CLOSING_AUCTION"
    case darkPoolAuction = "SECURITY_TRADING_STATUS_DARK_POOL_AUCTION"
    case discreteAuction = "SECURITY_TRADING_STATUS_DISCRETE_AUCTION"
    case openingAuctionPeriod = "SECURITY_TRADING_STATUS_OPENING_AUCTION_PERIOD"
    case tradingAtClosingAuctionPrice = "SECURITY_TRADING_STATUS_TRADING_AT_CLOSING_AUCTION_PRICE"
    case sessionAssigned = "SECURITY_TRADING_STATUS_SESSION_ASSIGNED"
    case sessionClose = "SECURITY_TRADING_STATUS_SESSION_CLOSE"
    case sessionOpen = "SECURITY_TRADING_STATUS_SESSION_OPEN"
    case dealerNormalTrading = "SECURITY_TRADING_STATUS_DEALER_NORMAL_TRADING"
    case dealerBreakInTrading = "SECURITY_TRADING_STATUS_DEALER_BREAK_IN_TRADING"
    case dealerNotAvailableForTrading = "SECURITY_TRADING_STATUS_DEALER_NOT_AVAILABLE_FOR_TRADING"
}
