//
// StopOrderTrailingData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct StopOrderTrailingData: Codable {
    /// Отступ.
    public var indent: Quotation?

    /// Тип величины отступа.
    public var indentType: TrailingValueType?

    /// Размер защитного спреда.
    public var spread: Quotation?

    /// Тип величины защитного спреда.
    public var spreadType: TrailingValueType?

    /// Статус трейлинг - стопа.
    public var status: TrailingStopStatus?

    /// Цена исполнения.
    public var price: Quotation?

    /// Локальный экстремум.
    public var extr: Quotation?

    public init(indent: Quotation? = nil, indentType: TrailingValueType? = nil, spread: Quotation? = nil, spreadType: TrailingValueType? = nil, status: TrailingStopStatus? = nil, price: Quotation? = nil, extr: Quotation? = nil) {
        self.indent = indent
        self.indentType = indentType
        self.spread = spread
        self.spreadType = spreadType
        self.status = status
        self.price = price
        self.extr = extr
    }
}
