//
// StopOrderType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Тип стоп-заявки. */

public enum StopOrderType: String, Codable {
    case unspecified = "STOP_ORDER_TYPE_UNSPECIFIED"
    case takeProfit = "STOP_ORDER_TYPE_TAKE_PROFIT"
    case stopLoss = "STOP_ORDER_TYPE_STOP_LOSS"
    case stopLimit = "STOP_ORDER_TYPE_STOP_LIMIT"
}
