//
// StopOrderExpirationType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Тип экспирации стоп-заявке. */

public enum StopOrderExpirationType: String, Codable {
    case unspecified = "STOP_ORDER_EXPIRATION_TYPE_UNSPECIFIED"
    case goodTillCancel = "STOP_ORDER_EXPIRATION_TYPE_GOOD_TILL_CANCEL"
    case goodTillDate = "STOP_ORDER_EXPIRATION_TYPE_GOOD_TILL_DATE"
}
