//
// TrailingStopStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public enum TrailingStopStatus: String, Codable {
    case unspecified = "TRAILING_STOP_UNSPECIFIED"
    case active = "TRAILING_STOP_ACTIVE"
    case activated = "TRAILING_STOP_ACTIVATED"
}
