//
// TrailingValueType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public enum TrailingValueType: String, Codable {
    case unspecified = "TRAILING_VALUE_UNSPECIFIED"

    /// Абсолютное значение в единицах цены
    case absolute = "TRAILING_VALUE_ABSOLUTE"

    /// Относительное значение в процентах
    case relative = "TRAILING_VALUE_RELATIVE"
}
