//
// VirtualPortfolioPosition.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct VirtualPortfolioPosition: Codable {
    public let instrumentUid: String
    public let figi: String
    public let positionUid: String
    public let instrumentType: String
    public let quantity: Quotation
    public let expireDate: Date

    public let currentPrice: MoneyValue?
    public let averagePositionPrice: MoneyValue?
    public let averagePositionPriceFifo: MoneyValue?
    public let expectedYield: Quotation?
    public let expectedYieldFifo: Quotation?
}
