//
// PostOrderResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Информация о выставлении поручения. */

public struct PostOrderResponse: Decodable {
    /// Биржевой идентификатор заявки.
    public let orderId: String

    /// Идентификатор ключа идемпотентности, переданный клиентом, в формате UID. Максимальная длина 36 символов.
    public let orderRequestId: String
    public let instrumentUid: String
    public let executionReportStatus: OrderExecutionReportStatus
    public let lotsRequested: String
    public let lotsExecuted: String
    public let initialOrderPrice: MoneyValue
    public let initialOrderPricePt: Quotation?
    public let executedOrderPrice: MoneyValue
    public let totalOrderAmount: MoneyValue
    public let initialCommission: MoneyValue
    public let executedCommission: MoneyValue
    public let figi: String
    public let direction: OrderDirection
    public let orderType: OrderType
    public let initialSecurityPrice: MoneyValue
    public let aciValue: MoneyValue?

    /// Дополнительные данные об исполнении заявки.
    public let message: String
    public let responseMetadata: ResponseMetadata?
}
