//
// PriceType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/// Тип цены.
/// Ответ в методах для фьючерсов и облигаций может возвращаться как в валюте расчетов, так и в пунктах цены.
/// Стоимость пункта может меняться в зависимости от курсовой разницы.
public enum PriceType: String, Codable {
    case unspecified = "PRICE_TYPE_UNSPECIFIED"

    /// Цена в пунктах (только для фьючерсов и облигаций).
    case point = "PRICE_TYPE_POINT"

    /// Цена в валюте расчётов по инструменту.
    case currency = "PRICE_TYPE_CURRENCY"
}
