//
// StopOrderStatusOption.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Статус стоп-заяки.  */

public enum StopOrderStatusOption: String, Codable {
    case unspecified = "STOP_ORDER_STATUS_UNSPECIFIED"
    case all = "STOP_ORDER_STATUS_ALL"
    case active = "STOP_ORDER_STATUS_ACTIVE"
    case executed = "STOP_ORDER_STATUS_EXECUTED"
    case canceled = "STOP_ORDER_STATUS_CANCELED"
    case expired = "STOP_ORDER_STATUS_EXPIRED"
}
