//
// TimeInForceType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public enum TimeInForceType: String, Codable {
    case unspecified = "TIME_IN_FORCE_UNSPECIFIED"
    case day = "TIME_IN_FORCE_DAY"
    case fillAndKill = "TIME_IN_FORCE_FILL_AND_KILL"
    case fillOrKill = "TIME_IN_FORCE_FILL_OR_KILL"
}
