//
// AccessLevel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Уровень доступа к счёту. */
public enum AccessLevel: String, Codable {
    case unspecified = "ACCOUNT_ACCESS_LEVEL_UNSPECIFIED"
    case fullAccess = "ACCOUNT_ACCESS_LEVEL_FULL_ACCESS"
    case readOnly = "ACCOUNT_ACCESS_LEVEL_READ_ONLY"
    case noAccess = "ACCOUNT_ACCESS_LEVEL_NO_ACCESS"
}