//
// AccountSubscriptionStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Счет клиента. */

public struct AccountSubscriptionStatus: Codable {

    public let accountId: String?
    public let subscriptionStatus: PortfolioSubscriptionStatus?

    public init(accountId: String? = nil, subscriptionStatus: PortfolioSubscriptionStatus? = nil) {
        self.accountId = accountId
        self.subscriptionStatus = subscriptionStatus
    }


}
