//
// AccruedInterest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Операция начисления купонов. */

public struct AccruedInterest: Codable {

    public let date: Date?
    public let value: Quotation?
    public let valuePercent: Quotation?
    public let nominal: Quotation?

    public init(date: Date? = nil, value: Quotation? = nil, valuePercent: Quotation? = nil, nominal: Quotation? = nil) {
        self.date = date
        self.value = value
        self.valuePercent = valuePercent
        self.nominal = nominal
    }


}
