//
// AssetRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Запрос актива по идентификатору. */

public struct AssetRequest: Codable {

    public let id: String?

    public init(id: String? = nil) {
        self.id = id
    }

}
