//
// AssetInstrument.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Идентификаторы инструмента. */

public struct AssetInstrument: Codable {

    public let uid: String?
    public let figi: String?
    public let instrumentType: String?
    public let ticker: String?
    public let classCode: String?
    public let links: [InstrumentLink]?
    public let instrumentKind: InstrumentType?

    public init(uid: String? = nil, figi: String? = nil, instrumentType: String? = nil, ticker: String? = nil, classCode: String? = nil, links: [InstrumentLink]? = nil, instrumentKind: InstrumentType? = nil) {
        self.uid = uid
        self.figi = figi
        self.instrumentType = instrumentType
        self.ticker = ticker
        self.classCode = classCode
        self.links = links
        self.instrumentKind = instrumentKind
    }


}
