//
// AssetSecurity.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Ценная бумага. */

public struct AssetSecurity: Codable {

    public let isin: String?
    public let type: String?
    public let instrumentKind: InstrumentType?
    public let share: AssetShare?
    public let bond: AssetBond?
    public let sp: AssetStructuredProduct?
    public let etf: AssetEtf?
    public let clearingCertificate: AssetClearingCertificate?

    public init(isin: String? = nil, type: String? = nil, instrumentKind: InstrumentType? = nil, share: AssetShare? = nil, bond: AssetBond? = nil, sp: AssetStructuredProduct? = nil, etf: AssetEtf? = nil, clearingCertificate: AssetClearingCertificate? = nil) {
        self.isin = isin
        self.type = type
        self.instrumentKind = instrumentKind
        self.share = share
        self.bond = bond
        self.sp = sp
        self.etf = etf
        self.clearingCertificate = clearingCertificate
    }


}
