//
// AssetFull.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AssetFull: Codable {

    public let uid: String?
    public let type: AssetType?
    public let name: String?
    public let nameBrief: String?
    public let description: String?
    public let deletedAt: Date?
    public let requiredTests: [String]?
    public let currency: AssetCurrency?
    public let security: AssetSecurity?
    public let gosRegCode: String?
    public let cfi: String?
    public let codeNsd: String?
    public let status: String?
    public let brand: Brand?
    public let updatedAt: Date?
    public let brCode: String?
    public let brCodeName: String?
    public let instruments: [AssetInstrument]?

    public init(uid: String? = nil, type: AssetType? = nil, name: String? = nil, nameBrief: String? = nil, description: String? = nil, deletedAt: Date? = nil, requiredTests: [String]? = nil, currency: AssetCurrency? = nil, security: AssetSecurity? = nil, gosRegCode: String? = nil, cfi: String? = nil, codeNsd: String? = nil, status: String? = nil, brand: Brand? = nil, updatedAt: Date? = nil, brCode: String? = nil, brCodeName: String? = nil, instruments: [AssetInstrument]? = nil) {
        self.uid = uid
        self.type = type
        self.name = name
        self.nameBrief = nameBrief
        self.description = description
        self.deletedAt = deletedAt
        self.requiredTests = requiredTests
        self.currency = currency
        self.security = security
        self.gosRegCode = gosRegCode
        self.cfi = cfi
        self.codeNsd = codeNsd
        self.status = status
        self.brand = brand
        self.updatedAt = updatedAt
        self.brCode = brCode
        self.brCodeName = brCodeName
        self.instruments = instruments
    }

}
