//
// AssetResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Данные по активу. */

public struct AssetResponse: Codable {

    public let asset: AssetFull?

    public init(asset: AssetFull? = nil) {
        self.asset = asset
    }


}
