//
// AssetsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Список активов. */

public struct AssetsResponse: Codable {

    public let assets: [Asset]?

    public init(assets: [Asset]? = nil) {
        self.assets = assets
    }


}
