//
// AssetStructuredProduct.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Структурная нота. */

public struct AssetStructuredProduct: Codable {

    public let borrowName: String?
    public let nominal: Quotation?
    public let nominalCurrency: String?
    public let type: StructuredProductType?
    public let logicPortfolio: String?
    public let assetType: AssetType?
    public let basicAsset: String?
    public let safetyBarrier: Quotation?
    public let maturityDate: Date?
    public let issueSizePlan: Quotation?
    public let issueSize: Quotation?
    public let placementDate: Date?
    public let issueKind: String?

    public init(borrowName: String? = nil, nominal: Quotation? = nil, nominalCurrency: String? = nil, type: StructuredProductType? = nil, logicPortfolio: String? = nil, assetType: AssetType? = nil, basicAsset: String? = nil, safetyBarrier: Quotation? = nil, maturityDate: Date? = nil, issueSizePlan: Quotation? = nil, issueSize: Quotation? = nil, placementDate: Date? = nil, issueKind: String? = nil) {
        self.borrowName = borrowName
        self.nominal = nominal
        self.nominalCurrency = nominalCurrency
        self.type = type
        self.logicPortfolio = logicPortfolio
        self.assetType = assetType
        self.basicAsset = basicAsset
        self.safetyBarrier = safetyBarrier
        self.maturityDate = maturityDate
        self.issueSizePlan = issueSizePlan
        self.issueSize = issueSize
        self.placementDate = placementDate
        self.issueKind = issueKind
    }


}
