//
// AssetType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Тип актива. */
public enum AssetType: String, Codable {
    case unspecified = "ASSET_TYPE_UNSPECIFIED"
    case currency = "ASSET_TYPE_CURRENCY"
    case commodity = "ASSET_TYPE_COMMODITY"
    case index = "ASSET_TYPE_INDEX"
    case security = "ASSET_TYPE_SECURITY"
}