//
// AssetEtf.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Фонд. */

public struct AssetEtf: Codable {

    public let totalExpense: Quotation?
    public let hurdleRate: Quotation?
    public let performanceFee: Quotation?
    public let fixedCommission: Quotation?
    public let paymentType: String?
    public let watermarkFlag: Bool?
    public let buyPremium: Quotation?
    public let sellDiscount: Quotation?
    public let rebalancingFlag: Bool?
    public let rebalancingFreq: String?
    public let managementType: String?
    public let primaryIndex: String?
    public let focusType: String?
    public let leveragedFlag: Bool?
    public let numShare: Quotation?
    public let ucitsFlag: Bool?
    public let releasedDate: Date?
    public let description: String?
    public let primaryIndexDescription: String?
    public let primaryIndexCompany: String?
    public let indexRecoveryPeriod: Quotation?
    public let inavCode: String?
    public let divYieldFlag: Bool?
    public let expenseCommission: Quotation?
    public let primaryIndexTrackingError: Quotation?
    public let rebalancingPlan: String?
    public let taxRate: String?
    public let rebalancingDates: [Date]?
    public let issueKind: String?
    public let nominal: Quotation?
    public let nominalCurrency: String?

    public init(totalExpense: Quotation? = nil, hurdleRate: Quotation? = nil, performanceFee: Quotation? = nil, fixedCommission: Quotation? = nil, paymentType: String? = nil, watermarkFlag: Bool? = nil, buyPremium: Quotation? = nil, sellDiscount: Quotation? = nil, rebalancingFlag: Bool? = nil, rebalancingFreq: String? = nil, managementType: String? = nil, primaryIndex: String? = nil, focusType: String? = nil, leveragedFlag: Bool? = nil, numShare: Quotation? = nil, ucitsFlag: Bool? = nil, releasedDate: Date? = nil, description: String? = nil, primaryIndexDescription: String? = nil, primaryIndexCompany: String? = nil, indexRecoveryPeriod: Quotation? = nil, inavCode: String? = nil, divYieldFlag: Bool? = nil, expenseCommission: Quotation? = nil, primaryIndexTrackingError: Quotation? = nil, rebalancingPlan: String? = nil, taxRate: String? = nil, rebalancingDates: [Date]? = nil, issueKind: String? = nil, nominal: Quotation? = nil, nominalCurrency: String? = nil) {
        self.totalExpense = totalExpense
        self.hurdleRate = hurdleRate
        self.performanceFee = performanceFee
        self.fixedCommission = fixedCommission
        self.paymentType = paymentType
        self.watermarkFlag = watermarkFlag
        self.buyPremium = buyPremium
        self.sellDiscount = sellDiscount
        self.rebalancingFlag = rebalancingFlag
        self.rebalancingFreq = rebalancingFreq
        self.managementType = managementType
        self.primaryIndex = primaryIndex
        self.focusType = focusType
        self.leveragedFlag = leveragedFlag
        self.numShare = numShare
        self.ucitsFlag = ucitsFlag
        self.releasedDate = releasedDate
        self.description = description
        self.primaryIndexDescription = primaryIndexDescription
        self.primaryIndexCompany = primaryIndexCompany
        self.indexRecoveryPeriod = indexRecoveryPeriod
        self.inavCode = inavCode
        self.divYieldFlag = divYieldFlag
        self.expenseCommission = expenseCommission
        self.primaryIndexTrackingError = primaryIndexTrackingError
        self.rebalancingPlan = rebalancingPlan
        self.taxRate = taxRate
        self.rebalancingDates = rebalancingDates
        self.issueKind = issueKind
        self.nominal = nominal
        self.nominalCurrency = nominalCurrency
    }

}
