//
// AssetShare.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Акция. */

public struct AssetShare: Codable {

    public let type: ShareType?
    public let issueSize: Quotation?
    public let nominal: Quotation?
    public let nominalCurrency: String?
    public let primaryIndex: String?
    public let dividendRate: Quotation?
    public let preferredShareType: String?
    public let ipoDate: Date?
    public let registryDate: Date?
    public let divYieldFlag: Bool?
    public let issueKind: String?
    public let placementDate: Date?
    public let represIsin: String?
    public let issueSizePlan: Quotation?
    public let totalFloat: Quotation?

    public init(type: ShareType? = nil, issueSize: Quotation? = nil, nominal: Quotation? = nil, nominalCurrency: String? = nil, primaryIndex: String? = nil, dividendRate: Quotation? = nil, preferredShareType: String? = nil, ipoDate: Date? = nil, registryDate: Date? = nil, divYieldFlag: Bool? = nil, issueKind: String? = nil, placementDate: Date? = nil, represIsin: String? = nil, issueSizePlan: Quotation? = nil, totalFloat: Quotation? = nil) {
        self.type = type
        self.issueSize = issueSize
        self.nominal = nominal
        self.nominalCurrency = nominalCurrency
        self.primaryIndex = primaryIndex
        self.dividendRate = dividendRate
        self.preferredShareType = preferredShareType
        self.ipoDate = ipoDate
        self.registryDate = registryDate
        self.divYieldFlag = divYieldFlag
        self.issueKind = issueKind
        self.placementDate = placementDate
        self.represIsin = represIsin
        self.issueSizePlan = issueSizePlan
        self.totalFloat = totalFloat
    }


}
