//
// AssetClearingCertificate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Клиринговый сертификат участия. */

public struct AssetClearingCertificate: Codable {

    public let nominal: Quotation?
    public let nominalCurrency: String?

    public init(nominal: Quotation? = nil, nominalCurrency: String? = nil) {
        self.nominal = nominal
        self.nominalCurrency = nominalCurrency
    }


}
