//
// AssetsRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Запрос списка активов. */

public struct AssetsRequest: Codable {




}
