//
// AssetBond.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Облигация. */

public struct AssetBond: Codable {

    public let currentNominal: Quotation?
    public let borrowName: String?
    public let issueSize: Quotation?
    public let nominal: Quotation?
    public let nominalCurrency: String?
    public let issueKind: String?
    public let interestKind: String?
    public let couponQuantityPerYear: Int?
    public let indexedNominalFlag: Bool?
    public let subordinatedFlag: Bool?
    public let collateralFlag: Bool?
    public let taxFreeFlag: Bool?
    public let amortizationFlag: Bool?
    public let floatingCouponFlag: Bool?
    public let perpetualFlag: Bool?
    public let maturityDate: Date?
    public let returnCondition: String?
    public let stateRegDate: Date?
    public let placementDate: Date?
    public let placementPrice: Quotation?
    public let issueSizePlan: Quotation?

    public init(currentNominal: Quotation? = nil, borrowName: String? = nil, issueSize: Quotation? = nil, nominal: Quotation? = nil, nominalCurrency: String? = nil, issueKind: String? = nil, interestKind: String? = nil, couponQuantityPerYear: Int? = nil, indexedNominalFlag: Bool? = nil, subordinatedFlag: Bool? = nil, collateralFlag: Bool? = nil, taxFreeFlag: Bool? = nil, amortizationFlag: Bool? = nil, floatingCouponFlag: Bool? = nil, perpetualFlag: Bool? = nil, maturityDate: Date? = nil, returnCondition: String? = nil, stateRegDate: Date? = nil, placementDate: Date? = nil, placementPrice: Quotation? = nil, issueSizePlan: Quotation? = nil) {
        self.currentNominal = currentNominal
        self.borrowName = borrowName
        self.issueSize = issueSize
        self.nominal = nominal
        self.nominalCurrency = nominalCurrency
        self.issueKind = issueKind
        self.interestKind = interestKind
        self.couponQuantityPerYear = couponQuantityPerYear
        self.indexedNominalFlag = indexedNominalFlag
        self.subordinatedFlag = subordinatedFlag
        self.collateralFlag = collateralFlag
        self.taxFreeFlag = taxFreeFlag
        self.amortizationFlag = amortizationFlag
        self.floatingCouponFlag = floatingCouponFlag
        self.perpetualFlag = perpetualFlag
        self.maturityDate = maturityDate
        self.returnCondition = returnCondition
        self.stateRegDate = stateRegDate
        self.placementDate = placementDate
        self.placementPrice = placementPrice
        self.issueSizePlan = issueSizePlan
    }


}
