//
// BondsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Список облигаций. */

public struct BondsResponse: Codable {

    public let instruments: [Bond]?

    public init(instruments: [Bond]? = nil) {
        self.instruments = instruments
    }


}
