//
// Brand.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Бренд. */

public struct Brand: Codable {

    public let uid: String?
    public let name: String?
    public let description: String?
    public let info: String?
    public let company: String?
    public let sector: String?
    public let countryOfRisk: String?
    public let countryOfRiskName: String?

    public init(uid: String? = nil, name: String? = nil, description: String? = nil, info: String? = nil, company: String? = nil, sector: String? = nil, countryOfRisk: String? = nil, countryOfRiskName: String? = nil) {
        self.uid = uid
        self.name = name
        self.description = description
        self.info = info
        self.company = company
        self.sector = sector
        self.countryOfRisk = countryOfRisk
        self.countryOfRiskName = countryOfRiskName
    }

}
