//
// BrokerReportRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BrokerReportRequest: Codable {

    public let generateBrokerReportRequest: GenerateBrokerReportRequest?
    public let getBrokerReportRequest: GetBrokerReportRequest?

    public init(generateBrokerReportRequest: GenerateBrokerReportRequest? = nil, getBrokerReportRequest: GetBrokerReportRequest? = nil) {
        self.generateBrokerReportRequest = generateBrokerReportRequest
        self.getBrokerReportRequest = getBrokerReportRequest
    }


}
