//
// BrokerReport.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BrokerReport: Codable {

    public let tradeId: String?
    public let orderId: String?
    public let figi: String?
    public let executeSign: String?
    public let tradeDatetime: Date?
    public let exchange: String?
    public let classCode: String?
    public let direction: String?
    public let name: String?
    public let ticker: String?
    public let price: MoneyValue?
    public let quantity: String?
    public let orderAmount: MoneyValue?
    public let aciValue: Quotation?
    public let totalOrderAmount: MoneyValue?
    public let brokerCommission: MoneyValue?
    public let exchangeCommission: MoneyValue?
    public let exchangeClearingCommission: MoneyValue?
    public let repoRate: Quotation?
    public let party: String?
    public let clearValueDate: Date?
    public let secValueDate: Date?
    public let brokerStatus: String?
    public let separateAgreementType: String?
    public let separateAgreementNumber: String?
    public let separateAgreementDate: String?
    public let deliveryType: String?

    public init(tradeId: String? = nil, orderId: String? = nil, figi: String? = nil, executeSign: String? = nil, tradeDatetime: Date? = nil, exchange: String? = nil, classCode: String? = nil, direction: String? = nil, name: String? = nil, ticker: String? = nil, price: MoneyValue? = nil, quantity: String? = nil, orderAmount: MoneyValue? = nil, aciValue: Quotation? = nil, totalOrderAmount: MoneyValue? = nil, brokerCommission: MoneyValue? = nil, exchangeCommission: MoneyValue? = nil, exchangeClearingCommission: MoneyValue? = nil, repoRate: Quotation? = nil, party: String? = nil, clearValueDate: Date? = nil, secValueDate: Date? = nil, brokerStatus: String? = nil, separateAgreementType: String? = nil, separateAgreementNumber: String? = nil, separateAgreementDate: String? = nil, deliveryType: String? = nil) {
        self.tradeId = tradeId
        self.orderId = orderId
        self.figi = figi
        self.executeSign = executeSign
        self.tradeDatetime = tradeDatetime
        self.exchange = exchange
        self.classCode = classCode
        self.direction = direction
        self.name = name
        self.ticker = ticker
        self.price = price
        self.quantity = quantity
        self.orderAmount = orderAmount
        self.aciValue = aciValue
        self.totalOrderAmount = totalOrderAmount
        self.brokerCommission = brokerCommission
        self.exchangeCommission = exchangeCommission
        self.exchangeClearingCommission = exchangeClearingCommission
        self.repoRate = repoRate
        self.party = party
        self.clearValueDate = clearValueDate
        self.secValueDate = secValueDate
        self.brokerStatus = brokerStatus
        self.separateAgreementType = separateAgreementType
        self.separateAgreementNumber = separateAgreementNumber
        self.separateAgreementDate = separateAgreementDate
        self.deliveryType = deliveryType
    }


}
