//
// BrokerReportResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BrokerReportResponse: Codable {

    public let generateBrokerReportResponse: GenerateBrokerReportResponse?
    public let getBrokerReportResponse: GetBrokerReportResponse?

    public init(generateBrokerReportResponse: GenerateBrokerReportResponse? = nil, getBrokerReportResponse: GetBrokerReportResponse? = nil) {
        self.generateBrokerReportResponse = generateBrokerReportResponse
        self.getBrokerReportResponse = getBrokerReportResponse
    }


}
