//
// CandleInstrument.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Запрос изменения статус подписки на свечи. */

public struct CandleInstrument: Codable {

    public let figi: String?
    public let interval: SubscriptionInterval?
    public let instrumentId: String?

    public init(figi: String? = nil, interval: SubscriptionInterval? = nil, instrumentId: String? = nil) {
        self.figi = figi
        self.interval = interval
        self.instrumentId = instrumentId
    }


}
