//
// CandleSubscription.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Статус подписки на свечи. */

public struct CandleSubscription: Codable {

    public let figi: String?
    public let interval: SubscriptionInterval?
    public let subscriptionStatus: SubscriptionStatus?
    public let instrumentUid: String?

    public init(figi: String? = nil, interval: SubscriptionInterval? = nil, subscriptionStatus: SubscriptionStatus? = nil, instrumentUid: String? = nil) {
        self.figi = figi
        self.interval = interval
        self.subscriptionStatus = subscriptionStatus
        self.instrumentUid = instrumentUid
    }


}
