//
// CandleInterval.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Интервал свечей. */
public enum CandleInterval: String, Codable {
    case unspecified = "CANDLE_INTERVAL_UNSPECIFIED"
    case _1min = "CANDLE_INTERVAL_1_MIN"
    case _5min = "CANDLE_INTERVAL_5_MIN"
    case _15min = "CANDLE_INTERVAL_15_MIN"
    case hour = "CANDLE_INTERVAL_HOUR"
    case day = "CANDLE_INTERVAL_DAY"
    case _2min = "CANDLE_INTERVAL_2_MIN"
    case _3min = "CANDLE_INTERVAL_3_MIN"
    case _10min = "CANDLE_INTERVAL_10_MIN"
    case _30min = "CANDLE_INTERVAL_30_MIN"
    case _2hour = "CANDLE_INTERVAL_2_HOUR"
    case _4hour = "CANDLE_INTERVAL_4_HOUR"
    case week = "CANDLE_INTERVAL_WEEK"
    case month = "CANDLE_INTERVAL_MONTH"
}
