//
// CloseSandboxAccountResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Результат закрытия счёта в песочнице. */

public struct CloseSandboxAccountResponse: Codable {




}
