//
// CountryResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Данные о стране. */

public struct CountryResponse: Codable {

    public let alfaTwo: String?
    public let alfaThree: String?
    public let name: String?
    public let nameBrief: String?

    public init(alfaTwo: String? = nil, alfaThree: String? = nil, name: String? = nil, nameBrief: String? = nil) {
        self.alfaTwo = alfaTwo
        self.alfaThree = alfaThree
        self.name = name
        self.nameBrief = nameBrief
    }


}
