//
// Coupon.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Объект передачи информации о купоне облигации. */

public struct Coupon: Codable {
    public let figi: String?
    public let couponDate: Date!
    public let couponNumber: String!
    public let fixDate: Date?
    public let payOneBond: MoneyValue!
    public let couponType: CouponType?
    public let couponStartDate: Date?
    public let couponEndDate: Date?
    public let couponPeriod: Int?

    public init(figi: String, couponDate: Date, couponNumber: String, fixDate: Date? = nil, payOneBond: MoneyValue, couponType: CouponType, couponStartDate: Date, couponEndDate: Date, couponPeriod: Int) {
        self.figi = figi
        self.couponDate = couponDate
        self.couponNumber = couponNumber
        self.fixDate = fixDate
        self.payOneBond = payOneBond
        self.couponType = couponType
        self.couponStartDate = couponStartDate
        self.couponEndDate = couponEndDate
        self.couponPeriod = couponPeriod
    }
    

}
