//
// CurrenciesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Данные по валютам. */

public struct CurrenciesResponse: Codable {

    public let instruments: [Currency]?

    public init(instruments: [Currency]? = nil) {
        self.instruments = instruments
    }


}
