//
// PortfolioRequestCurrencyRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum CurrencyRequest: String, Codable {
    case rub = "RUB"
    case usd = "USD"
    case eur = "EUR"
}
