//
// Dividend.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Информация о выплате. */

public struct Dividend: Codable {

    public let dividendNet: MoneyValue?
    public let paymentDate: Date?
    public let declaredDate: Date?
    public let lastBuyDate: Date?
    public let dividendType: String?
    public let recordDate: Date?
    public let regularity: String?
    public let closePrice: MoneyValue?
    public let yieldValue: Quotation?
    public let createdAt: Date?

    public init(dividendNet: MoneyValue? = nil, paymentDate: Date? = nil, declaredDate: Date? = nil, lastBuyDate: Date? = nil, dividendType: String? = nil, recordDate: Date? = nil, regularity: String? = nil, closePrice: MoneyValue? = nil, yieldValue: Quotation? = nil, createdAt: Date? = nil) {
        self.dividendNet = dividendNet
        self.paymentDate = paymentDate
        self.declaredDate = declaredDate
        self.lastBuyDate = lastBuyDate
        self.dividendType = dividendType
        self.recordDate = recordDate
        self.regularity = regularity
        self.closePrice = closePrice
        self.yieldValue = yieldValue
        self.createdAt = createdAt
    }


}
