//
// DividendsForeignIssuerReport.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Отчёт \&quot;Справка о доходах за пределами РФ\&quot;. */

public struct DividendsForeignIssuerReport: Codable {

    public let recordDate: Date?
    public let paymentDate: Date?
    public let securityName: String?
    public let isin: String?
    public let issuerCountry: String?
    public let quantity: String?
    public let dividend: Quotation?
    public let externalCommission: Quotation?
    public let dividendGross: Quotation?
    public let tax: Quotation?
    public let dividendAmount: Quotation?
    public let currency: String?

    public init(recordDate: Date? = nil, paymentDate: Date? = nil, securityName: String? = nil, isin: String? = nil, issuerCountry: String? = nil, quantity: String? = nil, dividend: Quotation? = nil, externalCommission: Quotation? = nil, dividendGross: Quotation? = nil, tax: Quotation? = nil, dividendAmount: Quotation? = nil, currency: String? = nil) {
        self.recordDate = recordDate
        self.paymentDate = paymentDate
        self.securityName = securityName
        self.isin = isin
        self.issuerCountry = issuerCountry
        self.quantity = quantity
        self.dividend = dividend
        self.externalCommission = externalCommission
        self.dividendGross = dividendGross
        self.tax = tax
        self.dividendAmount = dividendAmount
        self.currency = currency
    }


}
