//
// EditFavoritesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Результат редактирования списка избранных инструментов. */

public struct EditFavoritesResponse: Codable {

    public let favoriteInstruments: [FavoriteInstrument]?

    public init(favoriteInstruments: [FavoriteInstrument]? = nil) {
        self.favoriteInstruments = favoriteInstruments
    }


}
