//
// EditFavoritesActionType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Тип действия со списком избранных инструментов. */
public enum EditFavoritesActionType: String, Codable {
    case unspecified = "EDIT_FAVORITES_ACTION_TYPE_UNSPECIFIED"
    case add = "EDIT_FAVORITES_ACTION_TYPE_ADD"
    case del = "EDIT_FAVORITES_ACTION_TYPE_DEL"
}