//
// EditFavoritesRequestInstrument.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Массив инструментов для редактирования списка избранных инструментов. */

public struct EditFavoritesRequestInstrument: Codable {

    public let figi: String?

    public init(figi: String? = nil) {
        self.figi = figi
    }


}
