//
// EditFavoritesRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Запрос редактирования списка избранных инструментов. */

public struct EditFavoritesRequest: Codable {

    public let instruments: [EditFavoritesRequestInstrument]?
    public let actionType: EditFavoritesActionType?

    public init(instruments: [EditFavoritesRequestInstrument]? = nil, actionType: EditFavoritesActionType? = nil) {
        self.instruments = instruments
        self.actionType = actionType
    }


}
