//
// EtfResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Данные по фонду. */

public struct EtfResponse: Codable {

    public let instrument: Etf?

    public init(instrument: Etf? = nil) {
        self.instrument = instrument
    }


}
