//
// FavoriteInstrument.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Массив избранных инструментов. */

public struct FavoriteInstrument: Codable {

    public let figi: String?
    public let ticker: String?
    public let classCode: String?
    public let isin: String?
    public let instrumentType: String?
    public let otcFlag: Bool?
    public let apiTradeAvailableFlag: Bool?
    public let instrumentKind: InstrumentType?

    public init(figi: String? = nil, ticker: String? = nil, classCode: String? = nil, isin: String? = nil, instrumentType: String? = nil, otcFlag: Bool? = nil, apiTradeAvailableFlag: Bool? = nil, instrumentKind: InstrumentType? = nil) {
        self.figi = figi
        self.ticker = ticker
        self.classCode = classCode
        self.isin = isin
        self.instrumentType = instrumentType
        self.otcFlag = otcFlag
        self.apiTradeAvailableFlag = apiTradeAvailableFlag
        self.instrumentKind = instrumentKind
    }


}
