//
// FindInstrumentRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Запрос на поиск инструментов. */

public struct FindInstrumentRequest: Codable {

    public let query: String?

    public init(query: String? = nil) {
        self.query = query
    }


}
