//
// FutureResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Данные по фьючерсу. */

public struct FutureResponse: Codable {

    public let instrument: Future?

    public init(instrument: Future? = nil) {
        self.instrument = instrument
    }


}
