//
// Future.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Объект передачи информации о фьючерсе. */

public struct Future: Codable {

    public let figi: String?
    public let ticker: String?
    public let classCode: String?
    public let lot: Int?
    public let currency: String?
    public let klong: Quotation?
    public let kshort: Quotation?
    public let dlong: Quotation?
    public let dshort: Quotation?
    public let dlongMin: Quotation?
    public let dshortMin: Quotation?
    public let shortEnabledFlag: Bool?
    public let name: String?
    public let exchange: String?
    public let firstTradeDate: Date?
    public let lastTradeDate: Date?
    public let futuresType: String?
    public let assetType: String?
    public let basicAsset: String?
    public let basicAssetSize: Quotation?
    public let countryOfRisk: String?
    public let countryOfRiskName: String?
    public let sector: String?
    public let expirationDate: Date?
    public let tradingStatus: SecurityTradingStatus?
    public let otcFlag: Bool?
    public let buyAvailableFlag: Bool?
    public let sellAvailableFlag: Bool?
    public let minPriceIncrement: Quotation?
    public let apiTradeAvailableFlag: Bool?
    public let uid: String?
    public let realExchange: RealExchange?
    public let positionUid: String?
    public let basicAssetPositionUid: String?
    public let forIisFlag: Bool?
    public let forQualInvestorFlag: Bool?
    public let weekendFlag: Bool?
    public let blockedTcaFlag: Bool?
    public let first1minCandleDate: Date?
    public let first1dayCandleDate: Date?

    public init(figi: String? = nil, ticker: String? = nil, classCode: String? = nil, lot: Int? = nil, currency: String? = nil, klong: Quotation? = nil, kshort: Quotation? = nil, dlong: Quotation? = nil, dshort: Quotation? = nil, dlongMin: Quotation? = nil, dshortMin: Quotation? = nil, shortEnabledFlag: Bool? = nil, name: String? = nil, exchange: String? = nil, firstTradeDate: Date? = nil, lastTradeDate: Date? = nil, futuresType: String? = nil, assetType: String? = nil, basicAsset: String? = nil, basicAssetSize: Quotation? = nil, countryOfRisk: String? = nil, countryOfRiskName: String? = nil, sector: String? = nil, expirationDate: Date? = nil, tradingStatus: SecurityTradingStatus? = nil, otcFlag: Bool? = nil, buyAvailableFlag: Bool? = nil, sellAvailableFlag: Bool? = nil, minPriceIncrement: Quotation? = nil, apiTradeAvailableFlag: Bool? = nil, uid: String? = nil, realExchange: RealExchange? = nil, positionUid: String? = nil, basicAssetPositionUid: String? = nil, forIisFlag: Bool? = nil, forQualInvestorFlag: Bool? = nil, weekendFlag: Bool? = nil, blockedTcaFlag: Bool? = nil, first1minCandleDate: Date? = nil, first1dayCandleDate: Date? = nil) {
        self.figi = figi
        self.ticker = ticker
        self.classCode = classCode
        self.lot = lot
        self.currency = currency
        self.klong = klong
        self.kshort = kshort
        self.dlong = dlong
        self.dshort = dshort
        self.dlongMin = dlongMin
        self.dshortMin = dshortMin
        self.shortEnabledFlag = shortEnabledFlag
        self.name = name
        self.exchange = exchange
        self.firstTradeDate = firstTradeDate
        self.lastTradeDate = lastTradeDate
        self.futuresType = futuresType
        self.assetType = assetType
        self.basicAsset = basicAsset
        self.basicAssetSize = basicAssetSize
        self.countryOfRisk = countryOfRisk
        self.countryOfRiskName = countryOfRiskName
        self.sector = sector
        self.expirationDate = expirationDate
        self.tradingStatus = tradingStatus
        self.otcFlag = otcFlag
        self.buyAvailableFlag = buyAvailableFlag
        self.sellAvailableFlag = sellAvailableFlag
        self.minPriceIncrement = minPriceIncrement
        self.apiTradeAvailableFlag = apiTradeAvailableFlag
        self.uid = uid
        self.realExchange = realExchange
        self.positionUid = positionUid
        self.basicAssetPositionUid = basicAssetPositionUid
        self.forIisFlag = forIisFlag
        self.forQualInvestorFlag = forQualInvestorFlag
        self.weekendFlag = weekendFlag
        self.blockedTcaFlag = blockedTcaFlag
        self.first1minCandleDate = first1minCandleDate
        self.first1dayCandleDate = first1dayCandleDate
    }


}
