//
// FuturesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Данные по фьючерсам. */

public struct FuturesResponse: Codable {

    public let instruments: [Future]?

    public init(instruments: [Future]? = nil) {
        self.instruments = instruments
    }


}
