//
// GenerateDividendsForeignIssuerReportResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Объект результата задачи запуска формирования отчёта \&quot;Справка о доходах за пределами РФ\&quot;. */

public struct GenerateDividendsForeignIssuerReportResponse: Codable {

    public let taskId: String?

    public init(taskId: String? = nil) {
        self.taskId = taskId
    }


}
