//
// GenerateDividendsForeignIssuerReportRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Объект запроса формирования отчёта \&quot;Справка о доходах за пределами РФ\&quot;. */

public struct GenerateDividendsForeignIssuerReportRequest: Codable {

    public let accountId: String?
    public let from: Date?
    public let to: Date?

    public init(accountId: String? = nil, from: Date? = nil, to: Date? = nil) {
        self.accountId = accountId
        self.from = from
        self.to = to
    }


}
