//
// GenerateBrokerReportResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GenerateBrokerReportResponse: Codable {

    public let taskId: String?

    public init(taskId: String? = nil) {
        self.taskId = taskId
    }


}
