//
// GetAccruedInterestsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetAccruedInterestsResponse: Codable {

    public let accruedInterests: [AccruedInterest]?

    public init(accruedInterests: [AccruedInterest]? = nil) {
        self.accruedInterests = accruedInterests
    }


}
