//
// GetBrokerReportResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetBrokerReportResponse: Codable {

    public let brokerReport: [BrokerReport]?
    public let itemsCount: Int?
    public let pagesCount: Int?
    public let page: Int?

    public init(brokerReport: [BrokerReport]? = nil, itemsCount: Int? = nil, pagesCount: Int? = nil, page: Int? = nil) {
        self.brokerReport = brokerReport
        self.itemsCount = itemsCount
        self.pagesCount = pagesCount
        self.page = page
    }


}
