//
// GetBrandsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Список брендов. */

public struct GetBrandsResponse: Codable {

    public let brands: [Brand]?

    public init(brands: [Brand]? = nil) {
        self.brands = brands
    }


}
