//
// GetBrandRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Запрос бренда. */

public struct GetBrandRequest: Codable {

    public let id: String?

    public init(id: String? = nil) {
        self.id = id
    }

}
