//
// GetBrandsRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Запрос списка брендов. */

public struct GetBrandsRequest: Codable {




}
