//
// GetBrokerReportRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetBrokerReportRequest: Codable {

    public let taskId: String?
    public let page: Int?

    public init(taskId: String? = nil, page: Int? = nil) {
        self.taskId = taskId
        self.page = page
    }


}
