//
// GetClosePricesRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Запрос цен закрытия торговой сессии по инструментам. */

public struct GetClosePricesRequest: Codable {

    public let instruments: [InstrumentClosePriceRequest]?

    public init(instruments: [InstrumentClosePriceRequest]? = nil) {
        self.instruments = instruments
    }


}
