//
// GetCountriesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Справочник стран. */

public struct GetCountriesResponse: Codable {

    public let countries: [CountryResponse]?

    public init(countries: [CountryResponse]? = nil) {
        self.countries = countries
    }


}
