//
// GetCandlesRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Запрос исторических свечей. */

public struct GetCandlesRequest: Codable {

    public let figi: String?
    public let from: Date?
    public let to: Date?
    public let interval: CandleInterval?
    public let instrumentId: String?

    public init(figi: String? = nil, from: Date? = nil, to: Date? = nil, interval: CandleInterval? = nil, instrumentId: String? = nil) {
        self.figi = figi
        self.from = from
        self.to = to
        self.interval = interval
        self.instrumentId = instrumentId
    }


}
