//
// GetClosePricesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Цены закрытия торговой сессии по инструментам. */

public struct GetClosePricesResponse: Codable {

    public let closePrices: [InstrumentClosePriceResponse]?

    public init(closePrices: [InstrumentClosePriceResponse]? = nil) {
        self.closePrices = closePrices
    }


}
