//
// GetCountriesRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Запрос справочника стран. */

public struct GetCountriesRequest: Codable {




}
