//
// GetDividendsForeignIssuerResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetDividendsForeignIssuerResponse: Codable {

    public let generateDivForeignIssuerReportResponse: GenerateDividendsForeignIssuerReportResponse?
    public let divForeignIssuerReport: GetDividendsForeignIssuerReportResponse?

    public init(generateDivForeignIssuerReportResponse: GenerateDividendsForeignIssuerReportResponse? = nil, divForeignIssuerReport: GetDividendsForeignIssuerReportResponse? = nil) {
        self.generateDivForeignIssuerReportResponse = generateDivForeignIssuerReportResponse
        self.divForeignIssuerReport = divForeignIssuerReport
    }


}
