//
// GetDividendsForeignIssuerRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetDividendsForeignIssuerRequest: Codable {

    public let generateDivForeignIssuerReport: GenerateDividendsForeignIssuerReportRequest?
    public let getDivForeignIssuerReport: GetDividendsForeignIssuerReportRequest?

    public init(generateDivForeignIssuerReport: GenerateDividendsForeignIssuerReportRequest? = nil, getDivForeignIssuerReport: GetDividendsForeignIssuerReportRequest? = nil) {
        self.generateDivForeignIssuerReport = generateDivForeignIssuerReport
        self.getDivForeignIssuerReport = getDivForeignIssuerReport
    }


}
