//
// GetDividendsForeignIssuerReportResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetDividendsForeignIssuerReportResponse: Codable {

    public let dividendsForeignIssuerReport: [DividendsForeignIssuerReport]?
    public let itemsCount: Int?
    public let pagesCount: Int?
    public let page: Int?

    public init(dividendsForeignIssuerReport: [DividendsForeignIssuerReport]? = nil, itemsCount: Int? = nil, pagesCount: Int? = nil, page: Int? = nil) {
        self.dividendsForeignIssuerReport = dividendsForeignIssuerReport
        self.itemsCount = itemsCount
        self.pagesCount = pagesCount
        self.page = page
    }


}
