//
// GetDividendsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Дивиденды. */

public struct GetDividendsResponse: Codable {

    public let dividends: [Dividend]?

    public init(dividends: [Dividend]? = nil) {
        self.dividends = dividends
    }


}
