//
// GetFavoritesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** В ответ передаётся список избранных инструментов в качестве массива. */

public struct GetFavoritesResponse: Codable {

    public let favoriteInstruments: [FavoriteInstrument]?

    public init(favoriteInstruments: [FavoriteInstrument]? = nil) {
        self.favoriteInstruments = favoriteInstruments
    }


}
