//
// GetFuturesMarginRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetFuturesMarginRequest: Codable {

    public let figi: String?

    public init(figi: String? = nil) {
        self.figi = figi
    }


}
