//
// GetFavoritesRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Запрос списка избранных инструментов, входные параметры не требуются. */

public struct GetFavoritesRequest: Codable {




}
