//
// GetInfoRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Запрос информации о пользователе. */

public struct GetInfoRequest: Codable {




}
