//
// GetInfoResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Информация о пользователе. */

public struct GetInfoResponse: Codable {

    public let premStatus: Bool?
    public let qualStatus: Bool?
    public let qualifiedForWorkWith: [String]?
    public let tariff: String?

    public init(premStatus: Bool? = nil, qualStatus: Bool? = nil, qualifiedForWorkWith: [String]? = nil, tariff: String? = nil) {
        self.premStatus = premStatus
        self.qualStatus = qualStatus
        self.qualifiedForWorkWith = qualifiedForWorkWith
        self.tariff = tariff
    }


}
