//
// GetLastTradesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Обезличенных сделок за последний час. */

public struct GetLastTradesResponse: Codable {

    public let trades: [Trade]?

    public init(trades: [Trade]? = nil) {
        self.trades = trades
    }


}
