//
// GetLastTradesRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Запрос обезличенных сделок за последний час. */

public struct GetLastTradesRequest: Codable {

    public let figi: String?
    public let from: Date?
    public let to: Date?
    public let instrumentId: String?

    public init(figi: String? = nil, from: Date? = nil, to: Date? = nil, instrumentId: String? = nil) {
        self.figi = figi
        self.from = from
        self.to = to
        self.instrumentId = instrumentId
    }


}
