//
// GetMySubscriptions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Запрос активных подписок. */

public struct GetMySubscriptions: Codable {




}
