//
// GetMarginAttributesRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetMarginAttributesRequest: Codable {

    /** Идентификатор счёта пользователя. */
    public let accountId: String?

    public init(accountId: String? = nil) {
        self.accountId = accountId
    }


}
