//
// GetOrderStateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Запрос получения статуса торгового поручения. */

public struct GetOrderStateRequest: Codable {

    public let accountId: String?
    public let orderId: String?

    public init(accountId: String? = nil, orderId: String? = nil) {
        self.accountId = accountId
        self.orderId = orderId
    }


}
