//
// GetTradingStatusesRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Запрос получения торгового статуса. */

public struct GetTradingStatusesRequest: Codable {

    public let instrumentId: [String]?

    public init(instrumentId: [String]? = nil) {
        self.instrumentId = instrumentId
    }


}
