//
// GetTradingStatusResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Информация о торговом статусе. */

public struct GetTradingStatusResponse: Codable {

    public let figi: String?
    public let tradingStatus: SecurityTradingStatus?
    public let limitOrderAvailableFlag: Bool?
    public let marketOrderAvailableFlag: Bool?
    public let apiTradeAvailableFlag: Bool?
    public let instrumentUid: String?

    public init(figi: String? = nil, tradingStatus: SecurityTradingStatus? = nil, limitOrderAvailableFlag: Bool? = nil, marketOrderAvailableFlag: Bool? = nil, apiTradeAvailableFlag: Bool? = nil, instrumentUid: String? = nil) {
        self.figi = figi
        self.tradingStatus = tradingStatus
        self.limitOrderAvailableFlag = limitOrderAvailableFlag
        self.marketOrderAvailableFlag = marketOrderAvailableFlag
        self.apiTradeAvailableFlag = apiTradeAvailableFlag
        self.instrumentUid = instrumentUid
    }


}
