//
// GetUserTariffRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Запрос текущих лимитов пользователя. */

public struct GetUserTariffRequest: Codable {




}
