//
// InstrumentClosePriceRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Запрос цен закрытия торговой сессии по инструменту. */

public struct InstrumentClosePriceRequest: Codable {

    public let instrumentId: String?

    public init(instrumentId: String? = nil) {
        self.instrumentId = instrumentId
    }


}
