//
// InstrumentStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Статус запрашиваемых инструментов. */
public enum InstrumentStatus: String, Codable {
    case unspecified = "INSTRUMENT_STATUS_UNSPECIFIED"
    case base = "INSTRUMENT_STATUS_BASE"
    case all = "INSTRUMENT_STATUS_ALL"
}