//
// InstrumentShort.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Краткая информация об инструменте. */

public struct InstrumentShort: Codable {

    public let isin: String?
    public let figi: String?
    public let ticker: String?
    public let classCode: String?
    public let instrumentType: String?
    public let name: String?
    public let uid: String?
    public let positionUid: String?
    public let instrumentKind: InstrumentType?
    public let apiTradeAvailableFlag: Bool?
    public let forIisFlag: Bool?
    public let first1minCandleDate: Date?
    public let first1dayCandleDate: Date?
    public let forQualInvestorFlag: Bool?
    public let weekendFlag: Bool?
    public let blockedTcaFlag: Bool?

    public init(isin: String? = nil, figi: String? = nil, ticker: String? = nil, classCode: String? = nil, instrumentType: String? = nil, name: String? = nil, uid: String? = nil, positionUid: String? = nil, instrumentKind: InstrumentType? = nil, apiTradeAvailableFlag: Bool? = nil, forIisFlag: Bool? = nil, first1minCandleDate: Date? = nil, first1dayCandleDate: Date? = nil, forQualInvestorFlag: Bool? = nil, weekendFlag: Bool? = nil, blockedTcaFlag: Bool? = nil) {
        self.isin = isin
        self.figi = figi
        self.ticker = ticker
        self.classCode = classCode
        self.instrumentType = instrumentType
        self.name = name
        self.uid = uid
        self.positionUid = positionUid
        self.instrumentKind = instrumentKind
        self.apiTradeAvailableFlag = apiTradeAvailableFlag
        self.forIisFlag = forIisFlag
        self.first1minCandleDate = first1minCandleDate
        self.first1dayCandleDate = first1dayCandleDate
        self.forQualInvestorFlag = forQualInvestorFlag
        self.weekendFlag = weekendFlag
        self.blockedTcaFlag = blockedTcaFlag
    }


}
