//
// InstrumentsRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Запрос получения инструментов. */

public struct InstrumentsRequest: Codable {

    public let instrumentStatus: InstrumentStatus?

    public init(instrumentStatus: InstrumentStatus? = nil) {
        self.instrumentStatus = instrumentStatus
    }


}
