//
// InstrumentResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Данные по инструменту. */

public struct InstrumentResponse: Codable {

    public let instrument: Instrument?

    public init(instrument: Instrument? = nil) {
        self.instrument = instrument
    }


}
