//
// InstrumentLink.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Связь с другим инструментом. */

public struct InstrumentLink: Codable {

    public let type: String?
    public let instrumentUid: String?

    public init(type: String? = nil, instrumentUid: String? = nil) {
        self.type = type
        self.instrumentUid = instrumentUid
    }


}
