//
// InstrumentClosePriceResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Цена закрытия торговой сессии по инструменту. */

public struct InstrumentClosePriceResponse: Codable {

    public let figi: String?
    public let instrumentUid: String?
    public let price: Quotation?
    public let time: Date?

    public init(figi: String? = nil, instrumentUid: String? = nil, price: Quotation? = nil, time: Date? = nil) {
        self.figi = figi
        self.instrumentUid = instrumentUid
        self.price = price
        self.time = time
    }


}
