//
// LastPrice.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Информация о цене последней сделки. */

public struct LastPrice: Codable {

    public let figi: String?
    public let price: Quotation?
    public let time: Date?
    public let instrumentUid: String?

    public init(figi: String? = nil, price: Quotation? = nil, time: Date? = nil, instrumentUid: String? = nil) {
        self.figi = figi
        self.price = price
        self.time = time
        self.instrumentUid = instrumentUid
    }


}
