//
// LastPriceSubscription.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Статус подписки на цену последней сделки. */

public struct LastPriceSubscription: Codable {

    public let figi: String?
    public let subscriptionStatus: SubscriptionStatus?
    public let instrumentUid: String?

    public init(figi: String? = nil, subscriptionStatus: SubscriptionStatus? = nil, instrumentUid: String? = nil) {
        self.figi = figi
        self.subscriptionStatus = subscriptionStatus
        self.instrumentUid = instrumentUid
    }


}
