//
// MarketDataRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Запрос подписки или отписки на определённые биржевые данные. */

public struct MarketDataRequest: Codable {

    public let subscribeCandlesRequest: SubscribeCandlesRequest?
    public let subscribeOrderBookRequest: SubscribeOrderBookRequest?
    public let subscribeTradesRequest: SubscribeTradesRequest?
    public let subscribeInfoRequest: SubscribeInfoRequest?
    public let subscribeLastPriceRequest: SubscribeLastPriceRequest?
    /** Запрос активных подписок. */
    public let getMySubscriptions: GetMySubscriptions?

    public init(subscribeCandlesRequest: SubscribeCandlesRequest? = nil, subscribeOrderBookRequest: SubscribeOrderBookRequest? = nil, subscribeTradesRequest: SubscribeTradesRequest? = nil, subscribeInfoRequest: SubscribeInfoRequest? = nil, subscribeLastPriceRequest: SubscribeLastPriceRequest? = nil, getMySubscriptions: GetMySubscriptions? = nil) {
        self.subscribeCandlesRequest = subscribeCandlesRequest
        self.subscribeOrderBookRequest = subscribeOrderBookRequest
        self.subscribeTradesRequest = subscribeTradesRequest
        self.subscribeInfoRequest = subscribeInfoRequest
        self.subscribeLastPriceRequest = subscribeLastPriceRequest
        self.getMySubscriptions = getMySubscriptions
    }


}
