//
// MarketDataResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Пакет биржевой информации по подписке. */

public struct MarketDataResponse: Codable {

    public let subscribeCandlesResponse: SubscribeCandlesResponse?
    public let subscribeOrderBookResponse: SubscribeOrderBookResponse?
    public let subscribeTradesResponse: SubscribeTradesResponse?
    public let subscribeInfoResponse: SubscribeInfoResponse?
    public let candle: Candle?
    public let trade: Trade?
    public let orderbook: OrderBook?
    public let tradingStatus: TradingStatus?
    public let ping: Ping?
    public let subscribeLastPriceResponse: SubscribeLastPriceResponse?
    public let lastPrice: LastPrice?

    public init(subscribeCandlesResponse: SubscribeCandlesResponse? = nil, subscribeOrderBookResponse: SubscribeOrderBookResponse? = nil, subscribeTradesResponse: SubscribeTradesResponse? = nil, subscribeInfoResponse: SubscribeInfoResponse? = nil, candle: Candle? = nil, trade: Trade? = nil, orderbook: OrderBook? = nil, tradingStatus: TradingStatus? = nil, ping: Ping? = nil, subscribeLastPriceResponse: SubscribeLastPriceResponse? = nil, lastPrice: LastPrice? = nil) {
        self.subscribeCandlesResponse = subscribeCandlesResponse
        self.subscribeOrderBookResponse = subscribeOrderBookResponse
        self.subscribeTradesResponse = subscribeTradesResponse
        self.subscribeInfoResponse = subscribeInfoResponse
        self.candle = candle
        self.trade = trade
        self.orderbook = orderbook
        self.tradingStatus = tradingStatus
        self.ping = ping
        self.subscribeLastPriceResponse = subscribeLastPriceResponse
        self.lastPrice = lastPrice
    }


}
