//
// MoneyValue.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MoneyValue: Codable {

    public let currency: String?
    public let units: String?
    public let nano: Int?

    public init(currency: String? = nil, units: String? = nil, nano: Int? = nil) {
        self.currency = currency
        self.units = units
        self.nano = nano
    }


}
