//
// OpenSandboxAccountRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Запрос открытия счёта в песочнице. */

public struct OpenSandboxAccountRequest: Codable {




}
