//
// OpenSandboxAccountResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Номер открытого счёта в песочнице. */

public struct OpenSandboxAccountResponse: Codable {

    public let accountId: String?

    public init(accountId: String? = nil) {
        self.accountId = accountId
    }


}
