//
// OperationItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Данные об операции. */

public struct OperationItem: Codable {

    public let cursor: String?
    public let brokerAccountId: String?
    public let id: String?
    public let parentOperationId: String?
    public let name: String?
    public let date: Date?
    public let type: OperationType?
    public let description: String?
    public let state: OperationState?
    public let instrumentUid: String?
    public let figi: String?
    public let instrumentType: String?
    public let instrumentKind: InstrumentType?
    public let positionUid: String?
    public let payment: MoneyValue?
    public let price: MoneyValue?
    public let commission: MoneyValue?
    public let yield: MoneyValue?
    public let yieldRelative: Quotation?
    public let accruedInt: MoneyValue?
    public let quantity: String?
    public let quantityRest: String?
    public let quantityDone: String?
    public let cancelDateTime: Date?
    public let cancelReason: String?
    public let tradesInfo: OperationItemTrades?
    public let assetUid: String?

    public init(cursor: String? = nil, brokerAccountId: String? = nil, id: String? = nil, parentOperationId: String? = nil, name: String? = nil, date: Date? = nil, type: OperationType? = nil, description: String? = nil, state: OperationState? = nil, instrumentUid: String? = nil, figi: String? = nil, instrumentType: String? = nil, instrumentKind: InstrumentType? = nil, positionUid: String? = nil, payment: MoneyValue? = nil, price: MoneyValue? = nil, commission: MoneyValue? = nil, yield: MoneyValue? = nil, yieldRelative: Quotation? = nil, accruedInt: MoneyValue? = nil, quantity: String? = nil, quantityRest: String? = nil, quantityDone: String? = nil, cancelDateTime: Date? = nil, cancelReason: String? = nil, tradesInfo: OperationItemTrades? = nil, assetUid: String? = nil) {
        self.cursor = cursor
        self.brokerAccountId = brokerAccountId
        self.id = id
        self.parentOperationId = parentOperationId
        self.name = name
        self.date = date
        self.type = type
        self.description = description
        self.state = state
        self.instrumentUid = instrumentUid
        self.figi = figi
        self.instrumentType = instrumentType
        self.instrumentKind = instrumentKind
        self.positionUid = positionUid
        self.payment = payment
        self.price = price
        self.commission = commission
        self.yield = yield
        self.yieldRelative = yieldRelative
        self.accruedInt = accruedInt
        self.quantity = quantity
        self.quantityRest = quantityRest
        self.quantityDone = quantityDone
        self.cancelDateTime = cancelDateTime
        self.cancelReason = cancelReason
        self.tradesInfo = tradesInfo
        self.assetUid = assetUid
    }

}
