//
// OperationTrade.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Сделка по операции. */

public struct OperationTrade: Codable {

    public let tradeId: String?
    public let dateTime: Date?
    public let quantity: String?
    public let price: MoneyValue?

    public init(tradeId: String? = nil, dateTime: Date? = nil, quantity: String? = nil, price: MoneyValue? = nil) {
        self.tradeId = tradeId
        self.dateTime = dateTime
        self.quantity = quantity
        self.price = price
    }


}
