//
// OperationsRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Запрос получения списка операций по счёту. */

public struct OperationsRequest: Codable {

    public let accountId: String?
    public let from: Date?
    public let to: Date?
    public let state: OperationState?
    public let figi: String?

    public init(accountId: String? = nil, from: Date? = nil, to: Date? = nil, state: OperationState? = nil, figi: String? = nil) {
        self.accountId = accountId
        self.from = from
        self.to = to
        self.state = state
        self.figi = figi
    }


}
