//
// OperationsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Список операций. */

public struct OperationsResponse: Codable {

    public let operations: [AccountOperation]?

    public init(operations: [AccountOperation]? = nil) {
        self.operations = operations
    }


}
