//
// OperationItemTrade.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Сделка по операции. */

public struct OperationItemTrade: Codable {

    public let num: String?
    public let date: Date?
    public let quantity: String?
    public let price: MoneyValue?
    public let yield: MoneyValue?
    public let yieldRelative: Quotation?

    public init(num: String? = nil, date: Date? = nil, quantity: String? = nil, price: MoneyValue? = nil, yield: MoneyValue? = nil, yieldRelative: Quotation? = nil) {
        self.num = num
        self.date = date
        self.quantity = quantity
        self.price = price
        self.yield = yield
        self.yieldRelative = yieldRelative
    }


}
