//
// OperationItemTrades.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Массив с информацией о сделках. */

public struct OperationItemTrades: Codable {

    public let trades: [OperationItemTrade]?

    public init(trades: [OperationItemTrade]? = nil) {
        self.trades = trades
    }


}
