//
// Operation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Данные по операции. */

public struct AccountOperation: Codable {

    public let id: String?
    public let parentOperationId: String?
    public let currency: String?
    public let payment: MoneyValue?
    public let price: MoneyValue?
    public let state: OperationState?
    public let quantity: String?
    public let quantityRest: String?
    public let figi: String?
    public let instrumentType: String?
    public let date: Date?
    public let type: String?
    public let operationType: OperationType?
    public let trades: [OperationTrade]?
    public let assetUid: String?
    public let positionUid: String?
    public let instrumentUid: String?

    public init(id: String? = nil, parentOperationId: String? = nil, currency: String? = nil, payment: MoneyValue? = nil, price: MoneyValue? = nil, state: OperationState? = nil, quantity: String? = nil, quantityRest: String? = nil, figi: String? = nil, instrumentType: String? = nil, date: Date? = nil, type: String? = nil, operationType: OperationType? = nil, trades: [OperationTrade]? = nil, assetUid: String? = nil, positionUid: String? = nil, instrumentUid: String? = nil) {
        self.id = id
        self.parentOperationId = parentOperationId
        self.currency = currency
        self.payment = payment
        self.price = price
        self.state = state
        self.quantity = quantity
        self.quantityRest = quantityRest
        self.figi = figi
        self.instrumentType = instrumentType
        self.date = date
        self.type = type
        self.operationType = operationType
        self.trades = trades
        self.assetUid = assetUid
        self.positionUid = positionUid
        self.instrumentUid = instrumentUid
    }

}
