//
// OptionStyle.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Тип опциона по стилю. */
public enum OptionStyle: String, Codable {
    case unspecified = "OPTION_STYLE_UNSPECIFIED"
    case american = "OPTION_STYLE_AMERICAN"
    case european = "OPTION_STYLE_EUROPEAN"
}