//
// OptionSettlementType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Тип опциона по способу исполнения. */
public enum OptionSettlementType: String, Codable {
    case unspecified = "OPTION_EXECUTION_TYPE_UNSPECIFIED"
    case physicalDelivery = "OPTION_EXECUTION_TYPE_PHYSICAL_DELIVERY"
    case cashSettlement = "OPTION_EXECUTION_TYPE_CASH_SETTLEMENT"
}