//
// OptionDirection.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Тип опциона по направлению сделки. */
public enum OptionDirection: String, Codable {
    case unspecified = "OPTION_DIRECTION_UNSPECIFIED"
    case put = "OPTION_DIRECTION_PUT"
    case call = "OPTION_DIRECTION_CALL"
}