//
// OptionsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Данные по опционам. */

public struct OptionsResponse: Codable {

    public let instruments: [Option]?

    public init(instruments: [Option]? = nil) {
        self.instruments = instruments
    }


}
