//
// OptionResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Данные по опциону. */

public struct OptionResponse: Codable {

    public let instrument: Option?

    public init(instrument: Option? = nil) {
        self.instrument = instrument
    }


}
