//
// OrderBookSubscription.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Статус подписки. */

public struct OrderBookSubscription: Codable {

    public let figi: String?
    public let depth: Int?
    public let subscriptionStatus: SubscriptionStatus?
    public let instrumentUid: String?

    public init(figi: String? = nil, depth: Int? = nil, subscriptionStatus: SubscriptionStatus? = nil, instrumentUid: String? = nil) {
        self.figi = figi
        self.depth = depth
        self.subscriptionStatus = subscriptionStatus
        self.instrumentUid = instrumentUid
    }


}
