//
// OrderState.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Информация о торговом поручении. */

public struct OrderState: Codable {

    public let orderId: String?
    public let executionReportStatus: OrderExecutionReportStatus?
    public let lotsRequested: String?
    public let lotsExecuted: String?
    public let initialOrderPrice: MoneyValue?
    public let executedOrderPrice: MoneyValue?
    public let totalOrderAmount: MoneyValue?
    public let averagePositionPrice: MoneyValue?
    public let initialCommission: MoneyValue?
    public let executedCommission: MoneyValue?
    public let figi: String?
    public let direction: OrderDirection?
    public let initialSecurityPrice: MoneyValue?
    public let stages: [OrderStage]?
    public let serviceCommission: MoneyValue?
    public let currency: String?
    public let orderType: OrderType?
    public let orderDate: Date?
    public let instrumentUid: String?

    public init(orderId: String? = nil, executionReportStatus: OrderExecutionReportStatus? = nil, lotsRequested: String? = nil, lotsExecuted: String? = nil, initialOrderPrice: MoneyValue? = nil, executedOrderPrice: MoneyValue? = nil, totalOrderAmount: MoneyValue? = nil, averagePositionPrice: MoneyValue? = nil, initialCommission: MoneyValue? = nil, executedCommission: MoneyValue? = nil, figi: String? = nil, direction: OrderDirection? = nil, initialSecurityPrice: MoneyValue? = nil, stages: [OrderStage]? = nil, serviceCommission: MoneyValue? = nil, currency: String? = nil, orderType: OrderType? = nil, orderDate: Date? = nil, instrumentUid: String? = nil) {
        self.orderId = orderId
        self.executionReportStatus = executionReportStatus
        self.lotsRequested = lotsRequested
        self.lotsExecuted = lotsExecuted
        self.initialOrderPrice = initialOrderPrice
        self.executedOrderPrice = executedOrderPrice
        self.totalOrderAmount = totalOrderAmount
        self.averagePositionPrice = averagePositionPrice
        self.initialCommission = initialCommission
        self.executedCommission = executedCommission
        self.figi = figi
        self.direction = direction
        self.initialSecurityPrice = initialSecurityPrice
        self.stages = stages
        self.serviceCommission = serviceCommission
        self.currency = currency
        self.orderType = orderType
        self.orderDate = orderDate
        self.instrumentUid = instrumentUid
    }


}
