//
// OrderBook.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Пакет стаканов в рамках стрима. */

public struct OrderBook: Codable {

    public let figi: String?
    public let depth: Int?
    public let isConsistent: Bool?
    public let bids: [Order]?
    public let asks: [Order]?
    public let time: Date?
    public let limitUp: Quotation?
    public let limitDown: Quotation?
    public let instrumentUid: String?

    public init(figi: String? = nil, depth: Int? = nil, isConsistent: Bool? = nil, bids: [Order]? = nil, asks: [Order]? = nil, time: Date? = nil, limitUp: Quotation? = nil, limitDown: Quotation? = nil, instrumentUid: String? = nil) {
        self.figi = figi
        self.depth = depth
        self.isConsistent = isConsistent
        self.bids = bids
        self.asks = asks
        self.time = time
        self.limitUp = limitUp
        self.limitDown = limitDown
        self.instrumentUid = instrumentUid
    }


}
