//
// OrderExecutionReportStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum OrderExecutionReportStatus: String, Codable {
    case unspecified = "EXECUTION_REPORT_STATUS_UNSPECIFIED"
    case fill = "EXECUTION_REPORT_STATUS_FILL"
    case rejected = "EXECUTION_REPORT_STATUS_REJECTED"
    case cancelled = "EXECUTION_REPORT_STATUS_CANCELLED"
    case new = "EXECUTION_REPORT_STATUS_NEW"
    case partiallyfill = "EXECUTION_REPORT_STATUS_PARTIALLYFILL"
}