//
// Order.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Массив предложений/спроса. */

public struct Order: Codable {

    public let price: Quotation?
    public let quantity: String?

    public init(price: Quotation? = nil, quantity: String? = nil) {
        self.price = price
        self.quantity = quantity
    }


}
