//
// OrderType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Тип заявки. */
public enum OrderType: String, Codable {
    case unspecified = "ORDER_TYPE_UNSPECIFIED"
    case limit = "ORDER_TYPE_LIMIT"
    case market = "ORDER_TYPE_MARKET"
}