//
// OrderStage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Сделки в рамках торгового поручения. */

public struct OrderStage: Codable {

    public let price: MoneyValue?
    public let quantity: String?
    public let tradeId: String?

    public init(price: MoneyValue? = nil, quantity: String? = nil, tradeId: String? = nil) {
        self.price = price
        self.quantity = quantity
        self.tradeId = tradeId
    }


}
