//
// PortfolioResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Текущий портфель по счёту. */

public struct PortfolioResponse: Codable {

    public let totalAmountShares: MoneyValue?
    public let totalAmountBonds: MoneyValue?
    public let totalAmountEtf: MoneyValue?
    public let totalAmountCurrencies: MoneyValue?
    public let totalAmountFutures: MoneyValue?
    public let expectedYield: Quotation?
    public let positions: [PortfolioPosition]?
    public let accountId: String?
    public let totalAmountOptions: MoneyValue?
    public let totalAmountSp: MoneyValue?
    public let totalAmountPortfolio: MoneyValue?
    public let virtualPositions: [VirtualPortfolioPosition]?

    public init(totalAmountShares: MoneyValue? = nil, totalAmountBonds: MoneyValue? = nil, totalAmountEtf: MoneyValue? = nil, totalAmountCurrencies: MoneyValue? = nil, totalAmountFutures: MoneyValue? = nil, expectedYield: Quotation? = nil, positions: [PortfolioPosition]? = nil, accountId: String? = nil, totalAmountOptions: MoneyValue? = nil, totalAmountSp: MoneyValue? = nil, totalAmountPortfolio: MoneyValue? = nil, virtualPositions: [VirtualPortfolioPosition]? = nil) {
        self.totalAmountShares = totalAmountShares
        self.totalAmountBonds = totalAmountBonds
        self.totalAmountEtf = totalAmountEtf
        self.totalAmountCurrencies = totalAmountCurrencies
        self.totalAmountFutures = totalAmountFutures
        self.expectedYield = expectedYield
        self.positions = positions
        self.accountId = accountId
        self.totalAmountOptions = totalAmountOptions
        self.totalAmountSp = totalAmountSp
        self.totalAmountPortfolio = totalAmountPortfolio
        self.virtualPositions = virtualPositions
    }


}
