//
// PortfolioSubscriptionResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Объект результата подписки. */

public struct PortfolioSubscriptionResult: Codable {

    public let accounts: [AccountSubscriptionStatus]?

    public init(accounts: [AccountSubscriptionStatus]? = nil) {
        self.accounts = accounts
    }


}
