//
// PortfolioSubscriptionStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Результат подписки. */
public enum PortfolioSubscriptionStatus: String, Codable {
    case unspecified = "PORTFOLIO_SUBSCRIPTION_STATUS_UNSPECIFIED"
    case success = "PORTFOLIO_SUBSCRIPTION_STATUS_SUCCESS"
    case accountNotFound = "PORTFOLIO_SUBSCRIPTION_STATUS_ACCOUNT_NOT_FOUND"
    case internalError = "PORTFOLIO_SUBSCRIPTION_STATUS_INTERNAL_ERROR"
}