//
// PortfolioRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Запрос получения текущего портфеля по счёту. */

public struct PortfolioRequest: Codable {

    public let accountId: String?
    public let currency: CurrencyRequest?

    public init(accountId: String? = nil, currency: CurrencyRequest? = nil) {
        self.accountId = accountId
        self.currency = currency
    }


}
