//
// PositionsMoney.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Валютная позиция портфеля. */

public struct PositionsMoney: Codable {

    public let availableValue: MoneyValue?
    public let blockedValue: MoneyValue?

    public init(availableValue: MoneyValue? = nil, blockedValue: MoneyValue? = nil) {
        self.availableValue = availableValue
        self.blockedValue = blockedValue
    }


}
