//
// PositionsAccountSubscriptionStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Результат подписки. */
public enum PositionsAccountSubscriptionStatus: String, Codable {
    case unspecified = "POSITIONS_SUBSCRIPTION_STATUS_UNSPECIFIED"
    case success = "POSITIONS_SUBSCRIPTION_STATUS_SUCCESS"
    case accountNotFound = "POSITIONS_SUBSCRIPTION_STATUS_ACCOUNT_NOT_FOUND"
    case internalError = "POSITIONS_SUBSCRIPTION_STATUS_INTERNAL_ERROR"
}