//
// PositionsSubscriptionStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Счет клиента. */

public struct PositionsSubscriptionStatus: Codable {

    public let accountId: String?
    public let subscriptionStatus: PositionsAccountSubscriptionStatus?

    public init(accountId: String? = nil, subscriptionStatus: PositionsAccountSubscriptionStatus? = nil) {
        self.accountId = accountId
        self.subscriptionStatus = subscriptionStatus
    }


}
