//
// PositionsSecurities.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Баланс позиции ценной бумаги. */

public struct PositionsSecurities: Codable {

    public let figi: String?
    public let blocked: String?
    public let balance: String?
    public let positionUid: String?
    public let instrumentUid: String?
    public let exchangeBlocked: Bool?
    public let instrumentType: String?

    public init(figi: String? = nil, blocked: String? = nil, balance: String? = nil, positionUid: String? = nil, instrumentUid: String? = nil, exchangeBlocked: Bool? = nil, instrumentType: String? = nil) {
        self.figi = figi
        self.blocked = blocked
        self.balance = balance
        self.positionUid = positionUid
        self.instrumentUid = instrumentUid
        self.exchangeBlocked = exchangeBlocked
        self.instrumentType = instrumentType
    }


}
