//
// PositionData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Данные о позиции портфеля. */

public struct PositionData: Codable {

    public let accountId: String?
    public let money: [PositionsMoney]?
    public let securities: [PositionsSecurities]?
    public let futures: [PositionsFutures]?
    public let options: [PositionsOptions]?
    public let date: Date?

    public init(accountId: String? = nil, money: [PositionsMoney]? = nil, securities: [PositionsSecurities]? = nil, futures: [PositionsFutures]? = nil, options: [PositionsOptions]? = nil, date: Date? = nil) {
        self.accountId = accountId
        self.money = money
        self.securities = securities
        self.futures = futures
        self.options = options
        self.date = date
    }


}
