//
// PositionsOptions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Баланс опциона. */

public struct PositionsOptions: Codable {

    public let positionUid: String?
    public let instrumentUid: String?
    public let blocked: String?
    public let balance: String?

    public init(positionUid: String? = nil, instrumentUid: String? = nil, blocked: String? = nil, balance: String? = nil) {
        self.positionUid = positionUid
        self.instrumentUid = instrumentUid
        self.blocked = blocked
        self.balance = balance
    }


}
