//
// PositionsFutures.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Баланс фьючерса. */

public struct PositionsFutures: Codable {

    public let figi: String?
    public let blocked: String?
    public let balance: String?
    public let positionUid: String?
    public let instrumentUid: String?

    public init(figi: String? = nil, blocked: String? = nil, balance: String? = nil, positionUid: String? = nil, instrumentUid: String? = nil) {
        self.figi = figi
        self.blocked = blocked
        self.balance = balance
        self.positionUid = positionUid
        self.instrumentUid = instrumentUid
    }


}
