//
// PositionsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Список позиций по счёту. */

public struct PositionsResponse: Codable {

    public let money: [MoneyValue]?
    public let blocked: [MoneyValue]?
    public let securities: [PositionsSecurities]?
    public let limitsLoadingInProgress: Bool?
    public let futures: [PositionsFutures]?
    public let options: [PositionsOptions]?

    public init(money: [MoneyValue]? = nil, blocked: [MoneyValue]? = nil, securities: [PositionsSecurities]? = nil, limitsLoadingInProgress: Bool? = nil, futures: [PositionsFutures]? = nil, options: [PositionsOptions]? = nil) {
        self.money = money
        self.blocked = blocked
        self.securities = securities
        self.limitsLoadingInProgress = limitsLoadingInProgress
        self.futures = futures
        self.options = options
    }


}
