//
// PositionsRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Запрос позиций портфеля по счёту. */

public struct PositionsRequest: Codable {

    public let accountId: String?

    public init(accountId: String? = nil) {
        self.accountId = accountId
    }


}
