//
// PostStopOrderResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Результат выставления стоп-заявки. */

public struct PostStopOrderResponse: Codable {

    public let stopOrderId: String?

    public init(stopOrderId: String? = nil) {
        self.stopOrderId = stopOrderId
    }


}
