//
// PostOrderResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Информация о выставлении поручения. */

public struct PostOrderResponse: Codable {

    public let orderId: String?
    public let executionReportStatus: OrderExecutionReportStatus?
    public let lotsRequested: String?
    public let lotsExecuted: String?
    public let initialOrderPrice: MoneyValue?
    public let executedOrderPrice: MoneyValue?
    public let totalOrderAmount: MoneyValue?
    public let initialCommission: MoneyValue?
    public let executedCommission: MoneyValue?
    public let aciValue: MoneyValue?
    public let figi: String?
    public let direction: OrderDirection?
    public let initialSecurityPrice: MoneyValue?
    public let orderType: OrderType?
    public let message: String?
    public let initialOrderPricePt: Quotation?
    public let instrumentUid: String?

    public init(orderId: String? = nil, executionReportStatus: OrderExecutionReportStatus? = nil, lotsRequested: String? = nil, lotsExecuted: String? = nil, initialOrderPrice: MoneyValue? = nil, executedOrderPrice: MoneyValue? = nil, totalOrderAmount: MoneyValue? = nil, initialCommission: MoneyValue? = nil, executedCommission: MoneyValue? = nil, aciValue: MoneyValue? = nil, figi: String? = nil, direction: OrderDirection? = nil, initialSecurityPrice: MoneyValue? = nil, orderType: OrderType? = nil, message: String? = nil, initialOrderPricePt: Quotation? = nil, instrumentUid: String? = nil) {
        self.orderId = orderId
        self.executionReportStatus = executionReportStatus
        self.lotsRequested = lotsRequested
        self.lotsExecuted = lotsExecuted
        self.initialOrderPrice = initialOrderPrice
        self.executedOrderPrice = executedOrderPrice
        self.totalOrderAmount = totalOrderAmount
        self.initialCommission = initialCommission
        self.executedCommission = executedCommission
        self.aciValue = aciValue
        self.figi = figi
        self.direction = direction
        self.initialSecurityPrice = initialSecurityPrice
        self.orderType = orderType
        self.message = message
        self.initialOrderPricePt = initialOrderPricePt
        self.instrumentUid = instrumentUid
    }


}
