//
// PostOrderRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Запрос выставления торгового поручения. */

public struct PostOrderRequest: Codable {

    public let figi: String?
    public let quantity: String?
    public let price: Quotation?
    public let direction: OrderDirection?
    public let accountId: String?
    public let orderType: OrderType?
    public let orderId: String?
    public let instrumentId: String?

    public init(figi: String? = nil, quantity: String? = nil, price: Quotation? = nil, direction: OrderDirection? = nil, accountId: String? = nil, orderType: OrderType? = nil, orderId: String? = nil, instrumentId: String? = nil) {
        self.figi = figi
        self.quantity = quantity
        self.price = price
        self.direction = direction
        self.accountId = accountId
        self.orderType = orderType
        self.orderId = orderId
        self.instrumentId = instrumentId
    }


}
