//
// PriceType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Тип цены. */
public enum PriceType: String, Codable {
    case unspecified = "PRICE_TYPE_UNSPECIFIED"
    case point = "PRICE_TYPE_POINT"
    case currency = "PRICE_TYPE_CURRENCY"
}