//
// Quotation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Quotation: Codable {

    public let units: String?
    public let nano: Int?

    public init(units: String? = nil, nano: Int? = nil) {
        self.units = units
        self.nano = nano
    }


}
