//
// ReplaceOrderRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Запрос изменения выставленной заявки. */

public struct ReplaceOrderRequest: Codable {

    public let accountId: String?
    public let orderId: String?
    public let idempotencyKey: String?
    public let quantity: String?
    public let price: Quotation?
    public let priceType: PriceType?

    public init(accountId: String? = nil, orderId: String? = nil, idempotencyKey: String? = nil, quantity: String? = nil, price: Quotation? = nil, priceType: PriceType? = nil) {
        self.accountId = accountId
        self.orderId = orderId
        self.idempotencyKey = idempotencyKey
        self.quantity = quantity
        self.price = price
        self.priceType = priceType
    }


}
