//
// RpcStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RpcStatus: Codable {

    public let code: Int?
    public let message: String?
    public let details: [ProtobufAny]?

    public init(code: Int? = nil, message: String? = nil, details: [ProtobufAny]? = nil) {
        self.code = code
        self.message = message
        self.details = details
    }


}
