//
// SandboxPayInResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Результат пополнения счёта, текущий баланс. */

public struct SandboxPayInResponse: Codable {

    public let balance: MoneyValue?

    public init(balance: MoneyValue? = nil) {
        self.balance = balance
    }


}
