//
// SandboxPayInRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Запрос пополнения счёта в песочнице. */

public struct SandboxPayInRequest: Codable {

    public let accountId: String?
    public let amount: MoneyValue?

    public init(accountId: String? = nil, amount: MoneyValue? = nil) {
        self.accountId = accountId
        self.amount = amount
    }


}
