//
// ShareResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Данные по акции. */

public struct ShareResponse: Codable {

    public let instrument: Share?

    public init(instrument: Share? = nil) {
        self.instrument = instrument
    }


}
