//
// StopOrderDirection.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Направление сделки стоп-заявки. */
public enum StopOrderDirection: String, Codable {
    case unspecified = "STOP_ORDER_DIRECTION_UNSPECIFIED"
    case buy = "STOP_ORDER_DIRECTION_BUY"
    case sell = "STOP_ORDER_DIRECTION_SELL"
}