//
// StopOrder.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Информация о стоп-заявке. */

public struct StopOrder: Codable {

    public let stopOrderId: String?
    public let lotsRequested: String?
    public let figi: String?
    public let direction: StopOrderDirection?
    public let currency: String?
    public let orderType: StopOrderType?
    public let createDate: Date?
    public let activationDateTime: Date?
    public let expirationTime: Date?
    public let price: MoneyValue?
    public let stopPrice: MoneyValue?
    public let instrumentUid: String?

    public init(stopOrderId: String? = nil, lotsRequested: String? = nil, figi: String? = nil, direction: StopOrderDirection? = nil, currency: String? = nil, orderType: StopOrderType? = nil, createDate: Date? = nil, activationDateTime: Date? = nil, expirationTime: Date? = nil, price: MoneyValue? = nil, stopPrice: MoneyValue? = nil, instrumentUid: String? = nil) {
        self.stopOrderId = stopOrderId
        self.lotsRequested = lotsRequested
        self.figi = figi
        self.direction = direction
        self.currency = currency
        self.orderType = orderType
        self.createDate = createDate
        self.activationDateTime = activationDateTime
        self.expirationTime = expirationTime
        self.price = price
        self.stopPrice = stopPrice
        self.instrumentUid = instrumentUid
    }


}
