//
// StreamLimit.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Лимит stream-соединений. */

public struct StreamLimit: Codable {

    public let limit: Int?
    public let streams: [String]?

    public init(limit: Int? = nil, streams: [String]? = nil) {
        self.limit = limit
        self.streams = streams
    }


}
