//
// StructuredProductType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Тип структурной ноты. */
public enum StructuredProductType: String, Codable {
    case unspecified = "SP_TYPE_UNSPECIFIED"
    case deliverable = "SP_TYPE_DELIVERABLE"
    case nonDeliverable = "SP_TYPE_NON_DELIVERABLE"
}