//
// SubscribeOrderBookRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Запрос на изменение статуса подписки на стаканы. */

public struct SubscribeOrderBookRequest: Codable {

    public let subscriptionAction: SubscriptionAction?
    public let instruments: [OrderBookInstrument]?

    public init(subscriptionAction: SubscriptionAction? = nil, instruments: [OrderBookInstrument]? = nil) {
        self.subscriptionAction = subscriptionAction
        self.instruments = instruments
    }


}
