//
// SubscribeLastPriceRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Изменение статуса подписки на цену последней сделки по инструменту. */

public struct SubscribeLastPriceRequest: Codable {

    public let subscriptionAction: SubscriptionAction?
    public let instruments: [LastPriceInstrument]?

    public init(subscriptionAction: SubscriptionAction? = nil, instruments: [LastPriceInstrument]? = nil) {
        self.subscriptionAction = subscriptionAction
        self.instruments = instruments
    }


}
