//
// SubscriptionStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Результат подписки. */
public enum SubscriptionStatus: String, Codable {
    case unspecified = "SUBSCRIPTION_STATUS_UNSPECIFIED"
    case success = "SUBSCRIPTION_STATUS_SUCCESS"
    case instrumentNotFound = "SUBSCRIPTION_STATUS_INSTRUMENT_NOT_FOUND"
    case subscriptionActionIsInvalid = "SUBSCRIPTION_STATUS_SUBSCRIPTION_ACTION_IS_INVALID"
    case depthIsInvalid = "SUBSCRIPTION_STATUS_DEPTH_IS_INVALID"
    case intervalIsInvalid = "SUBSCRIPTION_STATUS_INTERVAL_IS_INVALID"
    case limitIsExceeded = "SUBSCRIPTION_STATUS_LIMIT_IS_EXCEEDED"
    case internalError = "SUBSCRIPTION_STATUS_INTERNAL_ERROR"
    case tooManyRequests = "SUBSCRIPTION_STATUS_TOO_MANY_REQUESTS"
}