//
// SubscribeLastPriceResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Результат изменения статуса подписки на цену последней сделки. */

public struct SubscribeLastPriceResponse: Codable {

    public let trackingId: String?
    public let lastPriceSubscriptions: [LastPriceSubscription]?

    public init(trackingId: String? = nil, lastPriceSubscriptions: [LastPriceSubscription]? = nil) {
        self.trackingId = trackingId
        self.lastPriceSubscriptions = lastPriceSubscriptions
    }


}
