//
// SubscribeInfoRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Изменение статуса подписки на торговый статус инструмента. */

public struct SubscribeInfoRequest: Codable {

    public let subscriptionAction: SubscriptionAction?
    public let instruments: [InfoInstrument]?

    public init(subscriptionAction: SubscriptionAction? = nil, instruments: [InfoInstrument]? = nil) {
        self.subscriptionAction = subscriptionAction
        self.instruments = instruments
    }


}
