//
// SubscriptionAction.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Тип операции со списком подписок. */
public enum SubscriptionAction: String, Codable {
    case unspecified = "SUBSCRIPTION_ACTION_UNSPECIFIED"
    case subscribe = "SUBSCRIPTION_ACTION_SUBSCRIBE"
    case unsubscribe = "SUBSCRIPTION_ACTION_UNSUBSCRIBE"
}