//
// SubscribeInfoResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Результат изменения статуса подписки на торговый статус. */

public struct SubscribeInfoResponse: Codable {

    public let trackingId: String?
    public let infoSubscriptions: [InfoSubscription]?

    public init(trackingId: String? = nil, infoSubscriptions: [InfoSubscription]? = nil) {
        self.trackingId = trackingId
        self.infoSubscriptions = infoSubscriptions
    }


}
