//
// SubscribeTradesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Результат изменения статуса подписки на поток обезличенных сделок. */

public struct SubscribeTradesResponse: Codable {

    public let trackingId: String?
    public let tradeSubscriptions: [TradeSubscription]?

    public init(trackingId: String? = nil, tradeSubscriptions: [TradeSubscription]? = nil) {
        self.trackingId = trackingId
        self.tradeSubscriptions = tradeSubscriptions
    }


}
