//
// SubscriptionInterval.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Интервал свечи. */
public enum SubscriptionInterval: String, Codable {
    case unspecified = "SUBSCRIPTION_INTERVAL_UNSPECIFIED"
    case oneMinute = "SUBSCRIPTION_INTERVAL_ONE_MINUTE"
    case fiveMinutes = "SUBSCRIPTION_INTERVAL_FIVE_MINUTES"
}