//
// SubscribeTradesRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Изменение статуса подписки на поток обезличенных сделок. */

public struct SubscribeTradesRequest: Codable {

    public let subscriptionAction: SubscriptionAction?
    public let instruments: [TradeInstrument]?

    public init(subscriptionAction: SubscriptionAction? = nil, instruments: [TradeInstrument]? = nil) {
        self.subscriptionAction = subscriptionAction
        self.instruments = instruments
    }


}
