//
// SubscribeOrderBookResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Результат изменения статуса подписки на стаканы. */

public struct SubscribeOrderBookResponse: Codable {

    public let trackingId: String?
    public let orderBookSubscriptions: [OrderBookSubscription]?

    public init(trackingId: String? = nil, orderBookSubscriptions: [OrderBookSubscription]? = nil) {
        self.trackingId = trackingId
        self.orderBookSubscriptions = orderBookSubscriptions
    }


}
