//
// SubscribeCandlesRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** subscribeCandles | Изменения статуса подписки на свечи. */

public struct SubscribeCandlesRequest: Codable {

    public let subscriptionAction: SubscriptionAction?
    public let instruments: [CandleInstrument]?
    public let waitingClose: Bool?

    public init(subscriptionAction: SubscriptionAction? = nil, instruments: [CandleInstrument]? = nil, waitingClose: Bool? = nil) {
        self.subscriptionAction = subscriptionAction
        self.instruments = instruments
        self.waitingClose = waitingClose
    }


}
