//
// SubscribeCandlesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Результат изменения статус подписки на свечи. */

public struct SubscribeCandlesResponse: Codable {

    public let trackingId: String?
    public let candlesSubscriptions: [CandleSubscription]?

    public init(trackingId: String? = nil, candlesSubscriptions: [CandleSubscription]? = nil) {
        self.trackingId = trackingId
        self.candlesSubscriptions = candlesSubscriptions
    }


}
