//
// TradingStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Пакет изменения торгового статуса. */

public struct TradingStatus: Codable {

    public let figi: String?
    public let tradingStatus: SecurityTradingStatus?
    public let time: Date?
    public let limitOrderAvailableFlag: Bool?
    public let marketOrderAvailableFlag: Bool?
    public let instrumentUid: String?

    public init(figi: String? = nil, tradingStatus: SecurityTradingStatus? = nil, time: Date? = nil, limitOrderAvailableFlag: Bool? = nil, marketOrderAvailableFlag: Bool? = nil, instrumentUid: String? = nil) {
        self.figi = figi
        self.tradingStatus = tradingStatus
        self.time = time
        self.limitOrderAvailableFlag = limitOrderAvailableFlag
        self.marketOrderAvailableFlag = marketOrderAvailableFlag
        self.instrumentUid = instrumentUid
    }


}
