//
// TradingSchedule.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Данные по торговой площадке. */

public struct TradingSchedule: Codable {

    public let exchange: String?
    public let days: [TradingDay]?

    public init(exchange: String? = nil, days: [TradingDay]? = nil) {
        self.exchange = exchange
        self.days = days
    }


}
