//
// TradingSchedulesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Список торговых площадок. */

public struct TradingSchedulesResponse: Codable {

    public let exchanges: [TradingSchedule]?

    public init(exchanges: [TradingSchedule]? = nil) {
        self.exchanges = exchanges
    }


}
