//
// TradeDirection.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Направление сделки. */
public enum TradeDirection: String, Codable {
    case unspecified = "TRADE_DIRECTION_UNSPECIFIED"
    case buy = "TRADE_DIRECTION_BUY"
    case sell = "TRADE_DIRECTION_SELL"
}