//
// Trade.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Информация о сделке. */

public struct Trade: Codable {

    public let figi: String?
    public let direction: TradeDirection?
    public let price: Quotation?
    public let quantity: String?
    public let time: Date?
    public let instrumentUid: String?

    public init(figi: String? = nil, direction: TradeDirection? = nil, price: Quotation? = nil, quantity: String? = nil, time: Date? = nil, instrumentUid: String? = nil) {
        self.figi = figi
        self.direction = direction
        self.price = price
        self.quantity = quantity
        self.time = time
        self.instrumentUid = instrumentUid
    }


}
