//
// TradingSchedulesRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Запрос расписания торгов. */

public struct TradingSchedulesRequest: Codable {

    public let exchange: String?
    public let from: Date?
    public let to: Date?

    public init(exchange: String? = nil, from: Date? = nil, to: Date? = nil) {
        self.exchange = exchange
        self.from = from
        self.to = to
    }


}
