//
// TradingDay.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Информация о времени торгов. */

public struct TradingDay: Codable {

    public let date: Date?
    public let isTradingDay: Bool?
    public let startTime: Date?
    public let endTime: Date?
    public let openingAuctionStartTime: Date?
    public let closingAuctionEndTime: Date?
    public let eveningOpeningAuctionStartTime: Date?
    public let eveningStartTime: Date?
    public let eveningEndTime: Date?
    public let clearingStartTime: Date?
    public let clearingEndTime: Date?
    public let premarketStartTime: Date?
    public let premarketEndTime: Date?
    public let closingAuctionStartTime: Date?
    public let openingAuctionEndTime: Date?

    public init(date: Date? = nil, isTradingDay: Bool? = nil, startTime: Date? = nil, endTime: Date? = nil, openingAuctionStartTime: Date? = nil, closingAuctionEndTime: Date? = nil, eveningOpeningAuctionStartTime: Date? = nil, eveningStartTime: Date? = nil, eveningEndTime: Date? = nil, clearingStartTime: Date? = nil, clearingEndTime: Date? = nil, premarketStartTime: Date? = nil, premarketEndTime: Date? = nil, closingAuctionStartTime: Date? = nil, openingAuctionEndTime: Date? = nil) {
        self.date = date
        self.isTradingDay = isTradingDay
        self.startTime = startTime
        self.endTime = endTime
        self.openingAuctionStartTime = openingAuctionStartTime
        self.closingAuctionEndTime = closingAuctionEndTime
        self.eveningOpeningAuctionStartTime = eveningOpeningAuctionStartTime
        self.eveningStartTime = eveningStartTime
        self.eveningEndTime = eveningEndTime
        self.clearingStartTime = clearingStartTime
        self.clearingEndTime = clearingEndTime
        self.premarketStartTime = premarketStartTime
        self.premarketEndTime = premarketEndTime
        self.closingAuctionStartTime = closingAuctionStartTime
        self.openingAuctionEndTime = openingAuctionEndTime
    }


}
