//
// UnaryLimit.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Лимит unary-методов. */

public struct UnaryLimit: Codable {

    public let limitPerMinute: Int?
    public let methods: [String]?

    public init(limitPerMinute: Int? = nil, methods: [String]? = nil) {
        self.limitPerMinute = limitPerMinute
        self.methods = methods
    }


}
