//
// WithdrawLimitsRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Запрос доступного для вывода остатка. */

public struct WithdrawLimitsRequest: Codable {

    public let accountId: String?

    public init(accountId: String? = nil) {
        self.accountId = accountId
    }


}
