//
// WithdrawLimitsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Доступный для вывода остаток. */

public struct WithdrawLimitsResponse: Codable {

    public let money: [MoneyValue]?
    public let blocked: [MoneyValue]?
    public let blockedGuarantee: [MoneyValue]?

    public init(money: [MoneyValue]? = nil, blocked: [MoneyValue]? = nil, blockedGuarantee: [MoneyValue]? = nil) {
        self.money = money
        self.blocked = blocked
        self.blockedGuarantee = blockedGuarantee
    }


}
